const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dayKey=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const today=()=>dayKey(); const dateLabel=d=>new Date(d+'T12:00:00').toLocaleDateString('de-DE',{day:'numeric',month:'long'});
const fmtSec=s=>`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`;
const fresh=()=>({version:1,goals:[],sessions:[],attempts:[],checks:[],reflections:[]});
let state=fresh();try{const saved=JSON.parse(localStorage.getItem('grundwissen-v1'));if(saved?.version===1)state={...fresh(),...saved};}catch{}
let storageOK=true;function save(){try{localStorage.setItem('grundwissen-v1',JSON.stringify(state));}catch{storageOK=false;}}

function removeLegacyDemoData(){
 let changed=Object.hasOwn(state,'demo')||Object.hasOwn(state,'demoDates');
 for(const key of ['sessions','goals','checks','attempts','reflections']){
  if(key==='goals')for(const goal of state.goals)if(goal.demo===true&&goal.updatedAt){delete goal.demo;changed=true;}
  const genuine=state[key].filter(item=>item.demo!==true);
  if(genuine.length!==state[key].length){state[key]=genuine;changed=true;}
 }
 for(const [number,date] of Object.entries(state.demoDates||{}))if(state.dates?.[number]===date)delete state.dates[number];
 delete state.demo;delete state.demoDates;
 if(changed)save();
}
removeLegacyDemoData();

let session=null,paused=false,lastTick=Date.now(),lastActive=Date.now(),exerciseIndex=0,hints=0,feedback=null,answerDraft='',noteDraft='',checkRun=null,confidence='',factor=2,termX=-2,weekOffset=0;
const icons={home:'M3 11 12 3l9 8v10h-6v-7H9v7H3z',learn:'M3 4h7l2 2 2-2h7v16h-7l-2 2-2-2H3z',goal:'M4 21V3m1 1h14l-3 5 3 5H5',chart:'M4 20V10m8 10V4m8 16v-7'};
const icon=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[n]}"/></svg>`;
const frac=(a,b)=>`<span class="fraction" aria-label="${a} durch ${b}"><span>${a}</span><span>${b}</span></span>`;
const title=id=>DATA.topics[id]?.title||id;
const route=()=>location.hash.slice(1)||'dashboard';
const topic=()=>route().split('/')[1]||'B02';
const currentModule=()=>MODULES[topic()]||MODULES.B02;
function toast(s){document.querySelector('.toast')?.remove();const el=document.createElement('div');el.className='toast';el.role='status';el.textContent=s;document.body.append(el);setTimeout(()=>el.remove(),3500);}
function go(s){if(route()===s)render();else location.hash=s;}
function minutes(sessions){return Math.floor(sessions.reduce((n,s)=>n+s.seconds,0)/60)}
function allSessions(){return session?[...state.sessions,session]:state.sessions}
function startSession(id){if(session?.topic===id)return;finishSession();session={id:crypto.randomUUID(),topic:id,date:today(),startedAt:new Date().toISOString(),seconds:0,reviewActivityTracked:true};paused=false;lastTick=Date.now();lastActive=Date.now();}
function flush(){if(!session)return;const now=Date.now(),delta=Math.min((now-lastTick)/1000,5);if(!paused&&!document.hidden&&now-lastActive<120000)session.seconds+=delta;lastTick=now;}
function finishSession(){flush();if(session?.seconds>0){state.sessions.push({...session,endedAt:new Date().toISOString()});save();}session=null;}
function latestCheck(id){return state.checks.filter(c=>c.topic===id).at(-1)}
function status(id){const c=latestCheck(id);if(c)return c.correct===c.total?'Im Check gelungen':'Noch üben';if(state.attempts.some(a=>a.topic===id))return 'Check noch offen';return 'Noch nicht geprüft';}
function pageHead(h,p,action=''){return `<div class="page-head"><div><h1>${h}</h1><p class="muted small">${p}</p></div>${action}</div>`;}
function render(){const r=route(),active=r.startsWith('learn')||r==='topics'?'topics':r.split('/')[0];$('#app').innerHTML=`<header><div class="brand"><span class="brandmark">=</span><div>Grundwissen<small>Mein Lernraum</small></div></div><div class="header-right">${session?`<span class="session" id="clock">${fmtSec(session.seconds)} aktiv</span><button data-action="pause">${paused?'Fortsetzen':'Pause'}</button>`:'<span class="muted small">Mathematik</span>'}</div></header><div class="layout"><aside><nav aria-label="Hauptnavigation"><div class="nav-label">MEIN LERNEN</div>${[['dashboard','home','Übersicht'],['topics','learn','Lernen'],['ai','learn','Lernen mit KI'],['goals','goal','Meine Ziele'],['progress','chart','Rückblick']].map(([path,i,t])=>`<a href="#${path}" class="${active===path?'active':''} ${path==='ai'?'ai-link':''}" ${active===path?'aria-current="page"':''}>${icon(i)}${t}</a>`).join('')}<div class="local-note">Dein Lernstand bleibt<br>auf diesem Gerät.<br><br>${Object.keys(MODULES).length} Themen zum Lernen</div></nav></aside><main id="main" tabindex="-1">${r==='dashboard'?dashboard():r==='topics'?topics():r.startsWith('learn/')?learn():r==='goals'?goals():r==='progress'?progress():(r==='tests'||r.startsWith('tests/'))?tests():r==='support'?supportPage():r==='ai'?aiOverview():dashboard()}<footer>${storageOK?'Lokal auf diesem Gerät gespeichert.':'Speichern ist in diesem Browser nicht möglich. Daten bleiben nur bis zum Schließen erhalten.'} <button type="button" class="quiet" data-export-progress="true" aria-label="Lernstand als JSON-Datei exportieren">Exportieren</button></footer></main></div>`;if(r.includes('/explain'))updateViz();bindForms();}
function weekCard(){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-(d.getDay()+6)%7+weekOffset*7);const days=Array.from({length:7},(_,i)=>{const t=new Date(d);t.setDate(t.getDate()+i);const key=dayKey(t);return {key,name:['Mo','Di','Mi','Do','Fr','Sa','So'][i],min:minutes(allSessions().filter(s=>s.date===key))}});const total=days.reduce((n,d)=>n+d.min,0);return `<div class="card-heading"><h2>${weekOffset===0?'Diese Woche':'Deine Lernwoche'}</h2><div><button class="quiet" data-action="week-prev" aria-label="Vorherige Woche">‹</button><button class="quiet" data-action="week-next" aria-label="Nächste Woche" ${weekOffset===0?'disabled':''}>›</button></div></div><div class="small muted">${dateLabel(days[0].key)} – ${dateLabel(days[6].key)}</div><div class="week">${days.map(d=>`<div class="day ${d.key===today()?'today':''}"><span>${d.min?d.min+'′':'–'}</span><div class="bar-slot"><div class="bar" style="height:${Math.max(2,d.min/Math.max(20,...days.map(x=>x.min))*62)}px"></div></div><span class="day-name">${d.name}</span></div>`).join('')}</div><div class="stats"><div><strong>${total}<span class="small"> min</span></strong><small>aktiv gelernt</small></div><div><strong>${days.filter(d=>d.min>0).length}<span class="small"> / 7</span></strong><small>Tage geübt</small></div></div>`;}
function getTests(){return DATA.tests.map(t=>({...t,date:state.dates?.[t.number]||t.date||'',example:!!state.dates?.[t.number]}));}
function nextTest(){return getTests().filter(t=>t.number>DATA.schedule.confirmed_completed_through&&t.date&&t.date>=today()).sort((a,b)=>a.date.localeCompare(b.date))[0];}
function testCard(){const t=nextTest();if(!t)return `<div class="eyebrow">Nächster Test</div><h2>Termin noch offen</h2><p class="muted">Die Themen stehen fest. In der vorliegenden Planung sind noch keine Termine eingetragen.</p><a class="button" href="#tests">Testplanung ansehen</a>`;const days=Math.round((new Date(t.date+'T12:00:00')-new Date(today()+'T12:00:00'))/86400000);return `<div class="row"><div class="eyebrow">Nächster Test</div><span class="badge">${days===0?'Heute':'In '+days+' Tagen'}</span></div><h2 class="test-title">Test ${String(t.number).padStart(3,'0')}</h2><div class="test-date"><strong>${dateLabel(t.date)}</strong><span class="small muted">${t.graded?'bewertet':'unbewertet'} · ${t.minutes} Minuten</span></div>${t.example?'<p class="small muted">Lokal angepasster Termin · Themen aus deiner Testplanung</p>':''}<div class="small muted">Neue Schwerpunkte</div>${t.new_topics.map(id=>`<div class="topic-line"><span>${id}</span><span>${esc(title(id))}</span></div>`).join('')}<p class="small muted">${t.graded?'Prüfbar sind alle bisher eröffneten Themen.':'Wiederholen: '+(t.review_topics.map(title).join(', ')||'neue Themen vertiefen')}.</p><div class="actions"><a class="button primary" href="#topics">Vorbereitung auswählen</a><a class="button" href="#tests">Alle Tests</a></div>`;}
function goalValue(g){const ss=allSessions().filter(s=>s.topic===g.topic&&s.date===g.date&&(!g.createdAt||new Date(s.startedAt)>=new Date(g.createdAt)));const sec=ss.reduce((n,s)=>n+s.seconds,0);const check=state.checks.some(c=>c.topic===g.topic&&c.date===g.date&&c.correct===c.total&&(!g.createdAt||new Date(c.at)>=new Date(g.createdAt)));return {sec,check,done:sec>=g.minutes*60&&(!g.check||check)};}
function goalCard(g){if(!g)return `<h2>Was nimmst du dir vor?</h2><p class="muted">Wähle ein Thema und einen festen Zeitpunkt. Ein kleines, konkretes Ziel reicht für den Anfang.</p><a class="button primary" href="#goals">Mein erstes Ziel setzen</a>`;const v=goalValue(g),late=g.date<today()&&!v.done;return `<div class="card-heading"><h2>Mein Lernziel</h2><a href="#goals" class="small">Anpassen</a></div><div class="goal-title">${esc(title(g.topic))}</div><p class="small muted">${dateLabel(g.date)}, ${esc(g.time)} Uhr · ${g.minutes} Minuten${g.check?' + Check':''}</p><div class="progress"><span style="width:${Math.min(100,v.sec/(g.minutes*60)*100)}%"></span></div><div class="row small"><span>${Math.floor(v.sec/60)} / ${g.minutes} Minuten</span><strong>${v.done?'Ziel erreicht':late?'Neu planen':g.date===today()?'Heute geplant':'Geplant'}</strong></div>${g.check?`<p class="small muted">Check: ${v.check?'ohne Hilfe gelungen':'noch offen'}</p>`:''}<a href="#learn/${g.topic}/explain" class="button wide" style="margin-top:16px">${v.done?'Weiter festigen':'Am Ziel arbeiten'}</a>`;}
function dashboard(){const next=state.goals.find(g=>!goalValue(g).done)||state.goals.at(-1);const gaps=Object.keys(MODULES).filter(id=>latestCheck(id)&&status(id)==='Noch üben');const recent=allSessions().slice(-3).reverse();return `${pageHead('Deine Übersicht',new Date().toLocaleDateString('de-DE',{weekday:'long',day:'numeric',month:'long',year:'numeric'}))}<div class="grid"><div class="stack"><section class="card">${testCard()}</section><section class="card"><div class="card-heading"><h2>Dein nächster Schritt</h2><span class="badge">${gaps.length?'Gezielt üben':'Selbst entscheiden'}</span></div><h3>${gaps.length?esc(title(gaps[0])):'Brüche: Warum bleibt der Wert gleich?'}</h3><p class="muted small">${gaps.length?'Im letzten Check waren noch Antworten offen. Entdecke den Zusammenhang und probiere anschließend neue Aufgaben.':'Verändere die Einteilung einer Fläche. Übe danach mit so viel Hilfe, wie du brauchst.'}</p><div class="actions"><a class="button primary" href="#learn/${gaps[0]||'B02'}/explain">Lernen beginnen</a><a class="button" href="#topics">Anderes Thema</a></div></section><section class="card"><h2>Zuletzt geübt</h2>${recent.length?recent.map(s=>`<div class="list-row"><div><strong class="small">${esc(title(s.topic))}</strong><p class="small muted">${dateLabel(s.date)} · ${fmtSec(s.seconds)} Minuten</p></div><a href="#learn/${s.topic}/practice" class="button" aria-label="${esc(title(s.topic))} weiterüben">Weiter</a></div>`).join(''):'<p class="empty small">Hier erscheinen deine Lerneinheiten, sobald du ein Thema bearbeitest.</p>'}</section></div><div class="stack"><section class="card">${goalCard(next)}</section><section class="card">${weekCard()}</section><section class="card"><div class="card-heading"><h2>Wo stehe ich?</h2><a href="#progress" class="small">Details</a></div>${Object.keys(MODULES).map(id=>`<div class="list-row"><div><strong class="small">${id==='B02'?'Kürzen & erweitern':'Werte einsetzen'}</strong><p class="small muted">${status(id)}</p></div><a href="#learn/${id}/check" class="text-link">Check</a></div>`).join('')}<p class="small muted">Ein Check ist eine Momentaufnahme. Wiederhole ihn später, um sicherer zu werden.</p></section></div></div>`;}
function topics(){return `${pageHead('Was möchtest du üben?','Wähle deinen Einstieg. Du kannst jederzeit zwischen Erklärung, Üben und Check wechseln.')}<div class="topic-grid">${Object.keys(MODULES).map(id=>`<section class="card topic-card"><div class="row"><span class="eyebrow">${id} · ${DATA.topics[id].area}</span><span class="badge">Interaktiv</span></div><h2>${esc(title(id))}</h2><p class="muted">${esc(DATA.topics[id].competence)}</p><p class="small">${status(id)}</p><div class="actions"><a class="button primary" href="#learn/${id}/explain">Entdecken</a><a class="button" href="#learn/${id}/practice">Üben</a><a class="button" href="#learn/${id}/check">Check</a></div></section>`).join('')}</div><section class="card sheet-list"><h2>Weitere Themen aus dem Material</h2><p class="muted small">Die interaktiven Lernwege werden schrittweise ergänzt. Die Themenübersicht ist bereits vollständig.</p><details><summary>Alle ${Object.keys(DATA.topics).length} Themen anzeigen</summary>${Object.entries(DATA.topics).filter(([id])=>!MODULES[id]).map(([id,t])=>`<div class="list-row"><span>${id} · ${esc(t.title)}</span><span class="badge">Noch nicht interaktiv</span></div>`).join('')}</details></section>`;}
function learn(){const id=topic();if(!MODULES[id])return topics();const step=route().split('/')[2]||'explain';return `<div class="learning">${pageHead(esc(title(id)),`${id} · ${esc(DATA.topics[id].area)}`,'<a class="button" href="#topics">Themen</a>')}<div class="tabs" aria-label="Lernschritte">${[['explain','1 · Entdecken'],['practice','2 · Üben'],['check','3 · Check']].map(([s,t])=>`<a href="#learn/${id}/${s}" class="${step===s?'active':''}" ${step===s?'aria-current="page"':''}>${t}</a>`).join('')}</div>${step==='explain'?explain(id):step==='practice'?practice(id):check(id)}</div>`;}
function explain(id){return `<section class="card"><h2>${id==='B02'?'Gleich viel Fläche. Andere Teilstücke.':'Ein Term ist ein Rechenplan.'}</h2><p>${id==='B02'?'Drei von vier gleich großen Teilen sind markiert. Beim Erweitern wird jedes Teil weiter unterteilt. Untersuche, was sich verändert – und was gleich bleibt.':'Die Variable x ist ein Platzhalter für eine Zahl. Verschiebe den Regler und verfolge, wie aus der Eingabe der Termwert entsteht.'}</p><div class="viz">${id==='B02'?`<div class="row small"><strong>Ausgangsbruch: ${frac(3,4)}</strong><span>Ein Ganzes</span></div><div class="fraction-bar" style="--n:4" role="img" aria-label="Drei von vier gleich großen Teilen markiert">${Array.from({length:4},(_,i)=>`<i class="${i<3?'fill':''}"></i>`).join('')}</div><div id="subdivision"></div><label class="slider-label" for="factor">Jedes Viertel unterteilen <output id="factor-value"></output></label><input id="factor" type="range" min="1" max="6" step="1" value="${factor}"><div class="row small muted"><span>1 Teil</span><span>6 Teile</span></div>`:`<div class="math">T(x) = 3x − 7</div><div id="term-flow"></div><label class="slider-label" for="term-x">Eingabe x <output id="x-value"></output></label><input id="term-x" type="range" min="-5" max="5" step="1" value="${termX}"><div class="row small muted"><span>−5</span><span>0</span><span>5</span></div>`}<div class="dynamic" id="dynamic-text" aria-live="polite"></div></div><h3>Darauf kommt es an</h3><p>${esc(DATA.topics[id].idea)}</p><details><summary>${id==='B02'?'Und wie funktioniert Kürzen?':'Warum brauche ich bei negativen Zahlen Klammern?'}</summary><p>${id==='B02'?'Lies die Darstellung rückwärts: Fasse die kleineren Teilstücke wieder zu Vierteln zusammen. Du teilst die Anzahl der markierten Teile und die Gesamtzahl durch denselben gemeinsamen Teiler. Die Fläche bleibt gleich.':'Setze die ganze Zahl mit ihrem Minuszeichen ein: 3 · (−2) − 7. So bleibt klar, dass mit −2 multipliziert wird. Erst die Multiplikation, dann die Subtraktion.'}</p></details><div class="actions"><a class="button primary" href="#learn/${id}/practice">Jetzt selbst üben</a><a class="button" href="#learn/${id}/check">Direkt zum Check</a></div></section>`;}
function updateViz(){if($('#factor')){const n=4*factor;$('#factor-value').textContent=`${factor} ${factor===1?'Teil':'Teile'}`;$('#subdivision').innerHTML=`<div class="row small"><strong>Erweitert: ${frac(3*factor,n)}</strong><span>Dasselbe Ganze</span></div><div class="fraction-bar" style="--n:${n}" role="img" aria-label="${3*factor} von ${n} gleich großen Teilen markiert">${Array.from({length:n},(_,i)=>`<i class="${i<3*factor?'fill':''}"></i>`).join('')}</div>`;$('#dynamic-text').innerHTML=`<strong>${3*factor} von ${n} Teilen sind markiert.</strong> Die Fläche bleibt gleich groß. Zähler und Nenner werden beide mit ${factor} multipliziert: <span class="nowrap">${frac(3,4)} = ${frac(3*factor,n)}</span>.`;}if($('#term-x')){$('#x-value').textContent=termX;$('#term-flow').innerHTML=`<div class="flow"><div class="flow-cell"><small>Eingabe x</small><strong>${termX}</strong></div><span>→</span><div class="flow-cell"><small>mal 3</small><strong>${termX*3}</strong></div><span>→</span><div class="flow-cell"><small>minus 7</small><strong>${termX*3-7}</strong></div></div>`;$('#dynamic-text').innerHTML=`Für <strong>x = ${termX}</strong> gilt: 3 · ${termX<0?'('+termX+')':termX} − 7 = <strong>${termX*3-7}</strong>.<br>Erhöhst du x um 1, steigt der Termwert um 3. Die −7 bleibt unverändert.`;}}
function practice(id){const tasks=MODULES[id].practice,q=tasks[exerciseIndex%tasks.length];return `<section class="card"><div class="row"><span class="eyebrow">Aufgabe ${exerciseIndex%tasks.length+1} von ${tasks.length}</span><span class="badge">${q.kind}</span></div><h2>${q.prompt}</h2><div class="math formula">${q.math}</div><form id="answer-form"><div class="field answer"><label for="answer">${q.label||'Dein Ergebnis'}</label><input id="answer" name="answer" value="${esc(answerDraft)}" autocomplete="off" inputmode="${q.fraction?'text':'decimal'}" placeholder="${q.fraction?'z. B. 3/4':'Zahl eingeben'}" required ${feedback?.correct?'disabled':''}></div><details ${noteDraft?'open':''}><summary>Meine Zwischenschritte notieren</summary><label for="notes" class="sr">Zwischenschritte</label><textarea id="notes" placeholder="Hier ist Platz für deinen Rechenweg. Er wird nicht automatisch bewertet.">${esc(noteDraft)}</textarea></details><div class="actions"><button class="primary" type="submit" ${feedback?.correct?'disabled':''}>Antwort prüfen</button><button type="button" data-action="hint" ${hints>=q.hints.length?'disabled':''}>${hints===0?'Kleine Hilfe':'Nächste Hilfe'} · ${hints}/${q.hints.length}</button></div></form><div aria-live="polite">${q.hints.slice(0,hints).map((h,i)=>`<div class="hint"><strong class="small">Hilfe ${i+1}</strong><br>${h}</div>`).join('')}${feedback?`<div class="feedback ${feedback.correct?'':'error'}"><strong>${feedback.correct?(hints?'Mit Hilfe gelöst.':'Das stimmt.'):'Noch nicht ganz.'}</strong><p>${feedback.message}</p></div>`:''}</div>${feedback?.correct?'<div class="actions"><button data-action="next-exercise" class="primary">Nächste Aufgabe</button><a class="button" href="#learn/'+id+'/check">Ohne Hilfe prüfen</a></div>':''}<div class="divider row"><span class="small muted">Du entscheidest, wie viel Unterstützung du brauchst.</span><a href="#learn/${id}/explain" class="small">Erklärung öffnen</a></div></section>`;}
function check(id){if(!checkRun||checkRun.topic!==id)return `<section class="card"><div class="eyebrow">Verständnischeck · 3 Fragen</div><h2>Was gelingt dir schon ohne Hilfe?</h2><p>Hier kommen neue Aufgaben und eine Frage zum Zusammenhang. Die Lösungen siehst du nach der Abgabe. Der Check ist unbenotet.</p><label>Wie sicher fühlst du dich gerade?</label><div class="pill-choice">${['Noch unsicher','Teils sicher','Ziemlich sicher'].map(c=>`<button data-confidence="${c}" class="${confidence===c?'selected':''}">${c}</button>`).join('')}</div><div class="actions"><button class="primary" data-action="start-check" ${!confidence?'disabled':''}>Check starten</button></div></section>`;if(checkRun.complete)return checkResult(id);const q=MODULES[id].check[checkRun.index];return `<section class="card"><p class="check-step">Frage ${checkRun.index+1} von 3 · Ohne Hilfen</p><h2>${q.prompt}</h2>${q.math?`<div class="math formula">${q.math}</div>`:''}<form id="check-form">${q.options?q.options.map((o,i)=>`<label class="option"><input type="radio" name="check-answer" value="${i}" required>${o}</label>`).join(''):`<div class="field answer"><label for="check-answer">${q.fraction?'Dein Bruch, z. B. 3/4':'Deine Antwort als Zahl'}</label><input id="check-answer" name="check-answer" autocomplete="off" inputmode="${q.fraction?'text':'decimal'}" required></div>`}<div class="actions"><button class="primary" type="submit">${checkRun.index===2?'Check auswerten':'Antwort übernehmen'}</button></div></form></section>`;}
function checkResult(id){const c=checkRun.record;return `<section class="card"><div class="eyebrow">Dein Ergebnis</div><h2>${c.correct} von ${c.total} Fragen richtig</h2><p>${c.correct===3?'Das ist dir in diesem Check selbstständig gelungen. Prüfe in ein paar Tagen noch einmal, was hängen geblieben ist.':'Hier kannst du gezielt weiterarbeiten. Eine falsche Antwort zeigt dir, was du als Nächstes untersuchen kannst.'}</p><div class="notice">Deine Einschätzung vorher: <strong>${esc(c.confidence)}</strong>. ${c.correct===3&&c.confidence==='Noch unsicher'?'Du konntest mehr, als du erwartet hast.':c.correct<2&&c.confidence==='Ziemlich sicher'?'Vergleiche deine Einschätzung mit den Antworten. Welche Stelle war schwieriger als gedacht?':'Passt dein Ergebnis zu deinem Gefühl?'}</div>${MODULES[id].check.map((q,i)=>`<details><summary>${c.answers[i].correct?'✓':'○'} Frage ${i+1}: ${c.answers[i].correct?'richtig':'noch üben'}</summary><p>${q.prompt}</p><p class="small">Deine Antwort: ${q.options?esc(q.options[Number(c.answers[i].value)]):esc(c.answers[i].value)}</p><p>${q.reason}</p></details>`).join('')}<form id="reflection-form" class="reflection"><label for="reflection">Was hilft dir beim nächsten Mal?</label><textarea id="reflection" required placeholder="Zum Beispiel: Ich prüfe, ob ich Zähler und Nenner durch dieselbe Zahl geteilt habe.">${esc(state.reflections.find(r=>r.checkId===c.id)?.text||'')}</textarea><div class="actions"><button type="submit">Reflexion speichern</button></div></form><div class="actions"><a class="button primary" href="#learn/${id}/${c.correct===3?'practice':'explain'}">${c.correct===3?'Weiter üben':'Zusammenhang noch einmal ansehen'}</a><a class="button" href="#goals">Nächstes Lernziel planen</a><button data-action="restart-check">Check wiederholen</button></div><p class="small muted">Bei einer direkten Wiederholung kennst du die Fragen bereits. Aussagekräftiger ist ein späterer Abruf.</p></section>`;}
function goals(){return `${pageHead('Meine Ziele','Was willst du üben – und wann passt es in deinen Tag?')}<div class="grid"><section class="card"><h2 id="goal-form-title">Ein konkretes Ziel setzen</h2><form id="goal-form"><input type="hidden" name="id"><div class="field"><label for="goal-topic">Ich möchte üben</label><select id="goal-topic" name="topic">${Object.keys(MODULES).map(id=>`<option value="${id}">${esc(title(id))}</option>`).join('')}</select></div><div class="form-grid"><div class="field"><label for="goal-date">Am</label><input id="goal-date" name="date" type="date" value="${today()}" min="${today()}" required></div><div class="field"><label for="goal-time">Um</label><input id="goal-time" name="time" type="time" value="16:00" required></div></div><div class="field"><label for="goal-minutes">So lange nehme ich mir Zeit</label><select id="goal-minutes" name="minutes">${[5,10,15,20,30].map(m=>`<option value="${m}" ${m===10?'selected':''}>${m} Minuten</option>`).join('')}</select></div><label class="option"><input type="checkbox" name="check" style="width:20px;min-height:20px">Danach den Check mit allen Antworten richtig abschließen</label><p class="small muted">Gezählt wird aktive Lernzeit zu diesem Thema am geplanten Tag, ab dem Anlegen des Ziels. Die Uhrzeit hilft dir bei der Planung; sie ist keine Frist.</p><div class="actions"><button class="primary" type="submit">Ziel speichern</button></div></form></section><div class="stack">${state.goals.length?state.goals.map(g=>`<section class="card">${goalCard(g)}<div class="actions"><button class="quiet" data-edit-goal="${g.id}">Ziel bearbeiten</button></div></section>`).join(''):'<section class="card"><h2>Klein anfangen</h2><p class="muted">„Am Dienstag um 16 Uhr übe ich zehn Minuten Brüche.“</p><p class="small">Du kannst dein Ziel später ändern. Ein nicht erreichtes Ziel ist ein Anlass, deinen Plan anzupassen.</p></section>'}</div></div>`;}
function recentLearningGaps(){
 const required=new Set(testScope()),stamp=x=>String(x?.at||x?.date||'');
 return Object.keys(MODULES).flatMap(id=>{
  if(['practised','mastered'].includes(state.statusOverrides?.[id]?.level))return [];
  const checks=state.checks.filter(c=>c.topic===id).sort((a,b)=>stamp(a).localeCompare(stamp(b))),last=checks.at(-1);
  const latest=new Map();
  for(const a of state.attempts.filter(a=>a.topic===id).sort((a,b)=>stamp(a).localeCompare(stamp(b))))latest.set((a.section||'practice')+':'+(a.taskId||'legacy'),a);
  const unresolved=[...latest.values()].filter(a=>a.correct===false&&(!last||stamp(a)>stamp(last)));
  const checkGap=last&&last.correct<last.total;
  if(!checkGap&&!unresolved.length)return [];
  return [{id,required:required.has(id),at:[checkGap?stamp(last):'',...unresolved.map(stamp)].sort().at(-1),reason:checkGap?'Im letzten Check: '+last.correct+' von '+last.total+' richtig.':unresolved.length===1?'Eine Aufgabe ist noch offen.':unresolved.length+' Aufgaben sind noch offen.'}];
 }).sort((a,b)=>Number(b.required)-Number(a.required)||b.at.localeCompare(a.at)||a.id.localeCompare(b.id)).slice(0,3);
}
function progress(){
 const c=state.checks.slice(-8).reverse(),gaps=recentLearningGaps(),sessions=allSessions().slice().sort((a,b)=>String(b.startedAt||b.date).localeCompare(String(a.startedAt||a.date))).slice(0,5);
 return `${pageHead('Mein Rückblick','Was hat funktioniert? Was ist dein nächster Schritt?')}<div class="grid"><div class="stack"><section class="card">${weekCard()}</section><section class="card"><h2>Meine Checks</h2>${c.length?c.map(x=>`<div class="list-row"><div><strong>${esc(title(x.topic))}</strong><p class="small muted">${dateLabel(x.date)} · ${x.correct}/${x.total} richtig · ohne Hilfe</p></div><a class="button" href="#learn/${x.topic}/explain">Weiterlernen</a></div>`).join(''):'<p class="empty">Noch kein Check abgeschlossen. Dein Lernstand bleibt bis dahin offen.</p>'}</section></div><div class="stack"><section class="card progress-gaps"><h2>Lücken gezielt schließen</h2>${gaps.length?gaps.map(g=>`<div class="list-row"><div><strong>${esc(title(g.id))}</strong><p class="small muted">${esc(g.reason)}</p></div><a class="button" href="#learn/${g.id}/practice" aria-label="${esc(title(g.id))} üben">Üben</a></div>`).join(''):'<p class="empty small">Aktuell sind keine offenen Lücken erkannt.</p>'}</section><section class="card"><h2>Meine Reflexionen</h2>${state.reflections.length?state.reflections.slice(-4).reverse().map(r=>`<div class="list-row"><div><p>${esc(r.text)}</p><span class="small muted">${dateLabel(r.date)}</span></div></div>`).join(''):'<p class="empty small">Nach einem Check kannst du festhalten, was dir beim nächsten Mal hilft.</p>'}</section></div></div><section class="card sheet-list progress-sessions"><h2>Wann habe ich geübt?</h2>${sessions.length?sessions.map(s=>`<div class="list-row"><span>${dateLabel(s.date)} · ${new Date(s.startedAt).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})} Uhr<br><span class="small muted">${esc(title(s.topic))}</span></span><strong>${fmtSec(s.seconds)} min</strong></div>`).join(''):'<p class="empty small">Deine Lerneinheiten erscheinen hier.</p>'}</section>`;
}
function tests(){return `${pageHead('Testplanung','Die Themen und der Umfang stammen aus der vorhandenen Wochenplanung.')}<div class="notice">Jeden Montag außerhalb der Ferien und Feiertage in Niedersachsen. Test 001 am 14.09.2026 ist bereits abgeschlossen. Änderungen hier gelten nur auf diesem Gerät.</div><section class="card test-list">${getTests().map(t=>`<div class="list-row"><strong>Test ${String(t.number).padStart(3,'0')}</strong><div style="flex:1"><h3>${t.new_topics.map(id=>esc(title(id))).join(' · ')}</h3><p class="small muted">${t.graded?'Bewertet · gesamter bisher eröffneter Stoff':'Unbewertet'} · ${t.minutes} Minuten</p>${t.graded?`<details><summary class="small">Gesamten Prüfungsstoff anzeigen</summary><p class="small">${t.assessment_scope.map(id=>id+' '+esc(title(id))).join(' · ')}</p></details>`:`<p class="small muted">Wiederholung: ${t.review_topics.map(id=>esc(title(id))).join(', ')||'neue Themen vertiefen'}</p>`}<label for="date-${t.number}">${t.example?'Lokal angepasster Termin':'Termin'}</label><input style="max-width:210px" type="date" id="date-${t.number}" data-test-date="${t.number}" value="${t.date}"></div></div>`).join('')}</section>`;}
function bindForms(){$('#answer-form')?.addEventListener('submit',e=>{e.preventDefault();const q=currentModule().practice[exerciseIndex%currentModule().practice.length],value=$('#answer').value;answerDraft=value;const result=q.validate(value);feedback={correct:result===true,message:result===true?q.reason:typeof result==='string'?result:'Prüfe deinen Rechenschritt. Du kannst dir eine kleine Hilfe holen.'};state.attempts.push({topic:topic(),taskId:q.id,value,correct:feedback.correct,hints,date:today(),at:new Date().toISOString(),notes:noteDraft});save();render();});$('#check-form')?.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.target),value=data.get('check-answer'),q=MODULES[checkRun.topic].check[checkRun.index];checkRun.answers.push({value,correct:q.validate(value)===true});if(checkRun.index===2){const record={id:crypto.randomUUID(),topic:checkRun.topic,date:today(),at:new Date().toISOString(),answers:checkRun.answers,correct:checkRun.answers.filter(x=>x.correct).length,total:3,confidence};state.checks.push(record);save();checkRun.complete=true;checkRun.record=record;}else checkRun.index++;render();});$('#goal-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),id=f.get('id'),old=state.goals.find(g=>g.id===id);const g={id:id||crypto.randomUUID(),topic:f.get('topic'),date:f.get('date'),time:f.get('time'),minutes:Number(f.get('minutes')),check:f.has('check'),createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(old)state.goals[state.goals.indexOf(old)]={...g,history:[...(old.history||[]),{...old,history:undefined}]};else state.goals.push(g);save();render();toast('Dein Lernziel ist gespeichert.');});$('#reflection-form')?.addEventListener('submit',e=>{e.preventDefault();const text=$('#reflection').value.trim();if(!text)return;const c=checkRun.record;state.reflections=state.reflections.filter(r=>r.checkId!==c.id);state.reflections.push({checkId:c.id,text,date:today()});save();toast('Deine Reflexion ist gespeichert.');});}
document.addEventListener('input',e=>{lastActive=Date.now();if(e.target.id==='factor'){factor=Number(e.target.value);updateViz();}if(e.target.id==='term-x'){termX=Number(e.target.value);updateViz();}if(e.target.id==='answer')answerDraft=e.target.value;if(e.target.id==='notes')noteDraft=e.target.value;});
document.addEventListener('change',e=>{if(e.target.dataset.testDate){state.dates??={};state.dates[e.target.dataset.testDate]=e.target.value;save();toast('Termin auf diesem Gerät gespeichert.');}});
document.addEventListener('click',e=>{lastActive=Date.now();const b=e.target.closest('button');if(!b)return;const a=b.dataset.action;if(b.dataset.confidence){confidence=b.dataset.confidence;render();}if(b.dataset.editGoal){const g=state.goals.find(x=>x.id===b.dataset.editGoal),f=$('#goal-form');f.elements.id.value=g.id;for(const k of ['topic','date','time','minutes'])f.elements[k].value=g[k];f.elements.check.checked=g.check;$('#goal-form-title').textContent='Lernziel anpassen';f.scrollIntoView({behavior:'smooth',block:'center'});f.elements.topic.focus();}if(a==='pause'){flush();paused=!paused;render();}if(a==='hint'){hints++;render();}if(a==='next-exercise'){exerciseIndex++;hints=0;feedback=null;answerDraft='';noteDraft='';render();}if(a==='start-check'){checkRun={topic:topic(),index:0,answers:[],complete:false};render();}if(a==='restart-check'){checkRun=null;confidence='';render();}if(a==='week-prev'){weekOffset--;render();}if(a==='week-next'){weekOffset=Math.min(0,weekOffset+1);render();}});
window.addEventListener('hashchange',()=>{flush();const id=route().startsWith('learn/')?topic():null;if(id&&MODULES[id])startSession(id);else finishSession();exerciseIndex=0;hints=0;feedback=null;answerDraft='';noteDraft='';render();window.scrollTo(0,0);});
for(const ev of ['pointerdown','keydown','touchstart','scroll'])document.addEventListener(ev,()=>lastActive=Date.now(),{passive:true});
document.addEventListener('visibilitychange',()=>{flush();if(document.hidden){if(session){state.sessions.push({...session});save();session={...session,id:crypto.randomUUID(),seconds:0,startedAt:new Date().toISOString(),date:today()};}}lastTick=Date.now();});
window.addEventListener('pagehide',()=>finishSession());setInterval(()=>{flush();if(session&&session.date!==today()){const id=session.topic;finishSession();startSession(id);}if($('#clock'))$('#clock').textContent=fmtSec(session.seconds)+(paused?' pausiert':Date.now()-lastActive>=120000?' · inaktiv':' aktiv');},1000);
if(route().startsWith('learn/')&&MODULES[topic()])startSession(topic());
if(document.modelContext?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'read_learning_overview',title:'Lernübersicht lesen',description:'Liest die auf diesem Gerät gespeicherten Lernziele und Check-Ergebnisse.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!input||Object.keys(input).length)throw new Error('Keine Parameter erwartet.');return {goals:state.goals.map(g=>({...g,progress:goalValue(g)})),topics:Object.keys(MODULES).filter(id=>state.attempts.some(a=>a.topic===id)||state.checks.some(c=>c.topic===id)||testScope().includes(id)).map(id=>({id,status:status(id)}))};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>lifecycle.abort());}
