// Source IDs refer to aufgabenbank.json. Explanation tasks are explicitly adapted to choice/order.
const field=(label,answer,kind='number')=>({label,answer,kind});
const task=(id,label,prompt,math,fields,reason,hints=[])=>({id,label,prompt,math,fields,reason,hints});
const choice=(q,options,correct)=>({...q,options,correct});
const ordering=(q,steps)=>({...q,steps});
const F=(label,a)=>field(label,a,'fraction');
MODULES.B02.practice=[
task('B02_L4_01','A1','Kürze vollständig.','35/49',[F('Gekürzter Bruch','5/7')],'35 und 49 durch 7 teilen: 35/49 = 5/7.',['Finde einen gemeinsamen Teiler von 35 und 49.','Beide Zahlen sind durch 7 teilbar.','35 : 7 = 5. Teile auch 49 durch 7.']),
task('B02_L4_02','A2','Erweitere auf den Nenner 30.','7/10',[F('Erweiterter Bruch','21/30')],'Der Faktor ist 3: 7 · 3 = 21 und 10 · 3 = 30.',['Wie wird aus 10 der Nenner 30?','Multipliziere beide Zahlen mit 3.','Der Nenner ist 30. Berechne jetzt 7 · 3.']),
task('B02_L4_03','B','Ergänze den fehlenden Nenner.','4/□ = 28/63',[field('Fehlender Nenner',9)],'28 : 7 = 4 und 63 : 7 = 9.',['Vergleiche die Zähler.','28 wird durch Teilen durch 7 zu 4.','Teile auch 63 durch 7.']),
choice(task('B02_L4_04','C','„15/25 = 3/25, denn ich habe durch 5 gekürzt.“ Wähle die richtige Verbesserung mit Begründung.','',[],'Richtig ist 3/5: Beide Zahlen müssen durch denselben gemeinsamen Teiler geteilt werden.',['Überlege, ob oben und unten dieselbe Änderung vorgenommen wurde.','Beim Kürzen muss sich auch der Nenner ändern.','15 : 5 = 3 und 25 : 5 = 5.']),['3/25 ist richtig: Es wurden fünfmal weniger Teile ausgewählt.','3/5 ist richtig: Zähler und Nenner werden beide durch 5 geteilt.','10/20 ist richtig: Kürzen bedeutet, von beiden Zahlen 5 abzuziehen.','15/5 ist richtig: Nur der Nenner beschreibt die Größe der Teile.'],1),
choice(task('B02_L4_05','D','Welche Brüche haben denselben Wert? Wähle die passende Begründung.','14/21; 10/15; 12/20',[],'14/21 und 10/15 ergeben 2/3. Dagegen ist 12/20 = 3/5.',['Kürze jeden Bruch vollständig.','14 und 21 sind durch 7, 10 und 15 durch 5 teilbar.','Die ersten beiden ergeben 2/3. Prüfe den dritten durch Teilen durch 4.']),['Alle drei: In jedem Bruch ist der Zähler kleiner als der Nenner.','14/21 und 12/20: Ihre Zähler sind beide gerade.','14/21 und 10/15: Beide ergeben 2/3; 12/20 ergibt 3/5.','10/15 und 12/20: Beide Nenner sind durch 5 teilbar.'],2)
];
MODULES.B02.pool=[
task('B02_POOL_01','01','Kürze vollständig.','12/16',[F('Gekürzter Bruch','3/4')],'Teile beide Zahlen durch 4. 3 und 4 haben keinen gemeinsamen Teiler größer als 1.',['Finde einen gemeinsamen Teiler.','12 und 16 sind durch 4 teilbar.','Berechne 12 : 4 und 16 : 4.']),
task('B02_POOL_02','02','Erweitere mit 4.','2/5',[F('Erweiterter Bruch','8/20')],'2 · 4 = 8 und 5 · 4 = 20.',['Verändere beide Zahlen mit demselben Faktor.','Multipliziere Zähler und Nenner mit 4.','2 · 4 = 8. Berechne noch den Nenner.']),
task('B02_POOL_03','03','Ergänze den fehlenden Zähler.','□/16 = 3/4',[field('Fehlender Zähler',12)],'4 · 4 = 16, also auch 3 · 4 = 12.',['Vergleiche die Nenner.','16 : 4 = 4 ist der Faktor.','Multipliziere den Zähler 3 mit 4.']),
task('B02_POOL_04','04','Bringe beide Brüche auf den kleinsten gemeinsamen Nenner.','1/4 und 1/5',[F('Erster Bruch','5/20'),F('Zweiter Bruch','4/20')],'20 ist das kleinste gemeinsame Vielfache von 4 und 5.',['Suche ein gemeinsames Vielfaches von 4 und 5.','Der kleinste gemeinsame Nenner ist 20.','Erweitere den ersten Bruch mit 5 und den zweiten mit 4.']),
choice(task('B02_NEU_01','05','Erweitere auf den Nenner 24. Wähle anschließend den richtigen Vergleich.','1/2; 2/3; 3/4',[F('1/2 erweitert','12/24'),F('2/3 erweitert','16/24'),F('3/4 erweitert','18/24')],'12 < 16 < 18. Bei demselben Ganzen ist die größere Anzahl gleich großer Teile der größere Anteil.',['Finde für jeden Nenner den Faktor zu 24.','Die Faktoren sind 12, 8 und 6.','Vergleiche anschließend die Zähler.']),['1/2 < 2/3 < 3/4, weil 12 < 16 < 18 bei gleichem Nenner.','1/2 > 2/3 > 3/4, weil größere Nenner immer kleinere Brüche bedeuten.','Alle sind gleich groß, weil der Nenner nun 24 ist.','2/3 ist am größten, weil hier mit dem Faktor 8 erweitert wird.'],0),
task('B02_NEU_02','06','Ergänze die drei Lücken.','3/□ = 9/24; □/35 = 4/5; 18/30 = 3/□',[field('Erste Lücke',8),field('Zweite Lücke',28),field('Dritte Lücke',5)],'Bei 9/24 werden Zähler und Nenner durch 3 geteilt: 3/8. Bei 4/5 werden beide mit 7 multipliziert: 28/35. Bei 18/30 werden beide durch 6 geteilt: 3/5.',['Suche in jedem Paar den gleichen Faktor für oben und unten.','Die Faktoren sind 3, 7 und 6.','Erstes Paar kürzen; zweites erweitern; drittes kürzen.']),
choice(task('B02_NEU_03','07','Welche Veränderung erhält den Wert? Wähle die beste Begründung.','4/6 → 6/8 oder 4/6 → 8/12',[],'Nur 8/12 hat denselben Wert wie 4/6. Multipliziere beide Zahlen mit 2.',['Prüfe, welche Rechenart verwendet wird.','Links wird 2 addiert, rechts mit 2 multipliziert.','Gleiches Addieren erhält einen Bruchwert im Allgemeinen nicht.']),['Beide: Zähler und Nenner werden jeweils gleich behandelt.','Nur 6/8: Zähler und Nenner wachsen um genau dieselbe Zahl.','Keine: Sobald der Nenner anders ist, ist auch der Bruchwert anders.','Nur 8/12: Beide Zahlen werden verdoppelt; der Anteil bleibt gleich.'],3),
task('B02_NEU_04','08','Kürze vollständig und gib den Prozentanteil an.','45/60',[F('Gekürzter Bruch','3/4'),field('Prozentanteil (ohne %)',75)],'45/60 = 3/4 = 75 %.',['Finde den größten gemeinsamen Teiler von 45 und 60.','Beide Zahlen lassen sich durch 15 teilen.','Ein Viertel sind 25 %.']),
task('B02_NEU_05','09','Finde drei verschiedene Brüche mit dem Wert 2/5. Einer soll den Zähler 18 haben.','',[F('Erster Bruch','equiv:2/5'),F('Zweiter Bruch','equiv:2/5'),F('Dritter Bruch','equiv:2/5')],'Zum Beispiel 4/10, 6/15 und 18/45. Alle entstehen durch Erweitern von 2/5.',['Erweitere mit verschiedenen positiven ganzen Zahlen.','Für den Zähler 18 brauchst du den Faktor 9.','Wähle für die anderen Brüche zwei andere Faktoren.']),
choice(task('B02_NEU_06','10','Kann 5/12 durch Erweitern einen Nenner 100 oder 1000 erhalten?', '',[],'Nein. 100 und 1000 sind keine ganzzahligen Vielfachen von 12. Der Faktor müsste aber eine positive ganze Zahl sein.',['Prüfe, ob 100 und 1000 Vielfache von 12 sind.','12 enthält den Primfaktor 3.','100 und 1000 sind nicht durch 3 teilbar.']),['Ja, beide: Jeder Bruch lässt sich auf jeden größeren Nenner erweitern.','Nur 100: Man kann beim Erweitern einen Faktor passend runden.','Keinen von beiden: Weder 100 noch 1000 ist ein ganzzahliges Vielfaches von 12.','Nur 1000: Ein genügend großer Nenner funktioniert immer.'],2)
];
MODULES.B02.check=[
task('B02_TEST_01','1','Kürze vollständig.','15/20',[F('Gekürzter Bruch','3/4')],'Teile Zähler und Nenner durch 5: 3/4.'),
task('B02_TEST_02','2','Erweitere mit 5.','2/5',[F('Erweiterter Bruch','10/25')],'2 · 5 = 10 und 5 · 5 = 25.'),
task('B02_TEST_03','3','Ergänze den fehlenden Zähler.','□/20 = 3/4',[field('Fehlender Zähler',15)],'Erweitere mit 5. Der Zähler wird 15.'),
task('B02_NEU_07','4','Von 42 gleich großen Feldern sind 30 markiert. Gib den Anteil vollständig gekürzt an.','',[F('Anteil','5/7')],'30/42 wird durch 6 gekürzt: 5/7.'),
choice(task('B02_NEU_08','5','Jemand kürzt 18/24 zu 9/8. Welche Erklärung trifft den Fehler am besten?','',[],'Oben wurde durch 2, unten durch 3 geteilt. Beide Zahlen müssen durch denselben Teiler geteilt werden; vollständig gekürzt ergibt sich 3/4.'),['Es wurde zu wenig gekürzt. Noch einmal nur den Zähler durch 3 teilen ergibt den richtigen Wert.','Zähler und Nenner wurden durch verschiedene Zahlen geteilt. Derselbe Teiler ist nötig; richtig ist 3/4.','Kürzen ist hier unmöglich, weil 18 und 24 nicht beide durch 5 teilbar sind.','Es hätte auf beiden Seiten 2 abgezogen werden müssen; der richtige Bruch ist 16/22.'],1)
];
MODULES.T01.practice=[
task('T01_L4_01','A1','Berechne den Termwert für a = 5.','18 − 2a',[field('Termwert',8)],'18 − 2 · 5 = 18 − 10 = 8.',['Setze 5 für a ein.','Multipliziere vor dem Subtrahieren.','2 · 5 = 10. Ziehe das von 18 ab.']),
task('T01_L4_02','A2','Setze t = −3 ein und berechne.','t² + 4t',[field('Termwert',-3)],'(−3)² + 4 · (−3) = 9 − 12 = −3.',['Setze beide Male (−3) ein.','Das Quadrat von −3 ist 9.','4 · (−3) = −12. Addiere zu 9.']),
task('T01_L4_03','B','Welcher Wert für b ergibt den Termwert 20?','4b + 8',[field('b',3)],'4 · 3 + 8 = 20.',['Rechne vom Ergebnis aus rückwärts.','Ziehe zuerst 8 von 20 ab.','4b = 12. Teile durch 4.']),
choice(task('T01_L4_04','C','„Für z = −4 ist 2z² = 64.“ Welche Korrektur erklärt den Fehler?','',[],'2z² = 2 · (−4)² = 32. Nur z wird quadriert. 64 wäre das Ergebnis von (2z)².',['Worauf bezieht sich die Hochzahl 2?','Der Faktor 2 steht außerhalb des Quadrats.','Rechne erst (−4)² = 16, dann mal 2.']),['−32 ist richtig, weil das Minus vor der 4 nach dem Quadrieren erhalten bleibt.','64 ist richtig, weil man 2 und z zuerst multiplizieren muss.','32 ist richtig: Nur z wird quadriert, der Faktor 2 wird danach multipliziert.','16 ist richtig, weil die 2 vor z durch das Quadrat ersetzt wird.'],2),
choice(task('T01_L4_05','D','Ein Dreieck hat Seiten x, x + 1 und x + 2 cm (x > 1). Wähle den Umfangsterm mit Begründung und berechne für x = 4.','',[field('Umfang bei x = 4 (cm)',15)],'U = x + (x + 1) + (x + 2) = 3x + 3. Bei x = 4 ist U = 15 cm.',['Addiere alle drei Seitenlängen.','Es gibt drei x und zusätzlich 1 + 2.','Setze 4 in 3x + 3 ein.']),['U = 3x + 3, weil die drei Seiten addiert werden.','U = 3x + 2, weil nur die längste zusätzliche Strecke zählt.','U = x(x + 1)(x + 2), weil ein Umfang aus dem Produkt aller Seiten entsteht.','U = 2x + 3, weil zwei Seiten für den Umfang ausreichen.'],0)
];
MODULES.T01.pool=[
task('T01_POOL_01','01','Berechne den Termwert für x = −2.','T(x) = 4x − 7',[field('Termwert',-15)],'4 · (−2) − 7 = −8 − 7 = −15.',['Setze die ganze Zahl (−2) ein.','Berechne zuerst 4 · (−2).','Ziehe 7 von −8 ab.']),
task('T01_POOL_02','02','Berechne für a = 3 und b = −1.','4a − 2b',[field('Termwert',14)],'4 · 3 − 2 · (−1) = 12 + 2 = 14.',['Setze beide Werte ein.','2 · (−1) = −2.','12 − (−2) entspricht 12 + 2.']),
ordering(task('T01_POOL_03','03','Ordne den Rechenplan von innen nach außen.','2(x + 4)²',[],'Eingabe wählen → 4 addieren → ganze Summe quadrieren → verdoppeln → Termwert erhalten.',['Beginne bei der Eingabe.','Die Klammer wird vor dem Quadrat gerechnet.','Die Multiplikation mit 2 kommt nach dem Quadrieren.']),['Einen Wert für x wählen.','Zu diesem Wert 4 addieren.','Die gesamte entstandene Summe quadrieren.','Dieses Quadrat mit 2 multiplizieren.','Das Ergebnis als Termwert angeben.']),
choice(task('T01_POOL_04','04','Ein Heft kostet 4 Euro, der Versand einmalig 4 Euro. Wähle den passenden Term für x Hefte und berechne für x = 5.','',[field('Preis für 5 Hefte (€)',24)],'4x + 4. Der Versand fällt nur einmal an: 4 · 5 + 4 = 24 Euro.',['Welche Kosten fallen für jedes Heft an?','Der Versand ist unabhängig von der Anzahl.','Rechne 5 · 4 und addiere einmal 4.']),['8x, weil Heftpreis und Versand für jedes Heft zusammengezählt werden.','4x + 4, weil der Heftpreis pro Heft und der Versand einmal anfallen.','4x², weil vier Euro mit der Anzahl zweimal multipliziert werden.','x + 8, weil zur Anzahl beide Preise addiert werden.'],1),
choice(task('T01_NEU_01','05','Berechne die drei Termwerte. Welche Änderung gilt pro zusätzlichem x-Schritt?','T(x) = 3x − 2',[field('T(−1)',-5),field('T(0)',-2),field('T(2)',4)],'Die Termwerte sind −5, −2 und 4. Pro Zunahme von x um 1 wächst T um 3; von x = 0 zu x = 2 sind es zwei Schritte.',['Setze die Werte einzeln ein.','Die Eingaben steigen zuerst um 1, dann um 2.','Der Faktor vor x legt die Änderung pro x-Schritt fest.']),['Der Termwert steigt pro x-Schritt um 2.','Der Termwert steigt pro x-Schritt um 1.','Der Termwert steigt pro x-Schritt um 3.','Der Termwert wird bei jedem x-Schritt verdreifacht.'],2),
choice(task('T01_NEU_02','06','Eine Eingabe wird verdoppelt. Dann wird 3 addiert und das Ergebnis quadriert. Welcher Term passt?','',[],'(2x + 3)² quadriert die gesamte entstandene Summe.',['Das Quadrat muss die ganze Summe betreffen.','Verdoppeln bedeutet 2x.','Setze 2x + 3 gemeinsam in eine Klammer.']),['2x + 3²','2(x + 3)²','(2x)² + 3','(2x + 3)²'],3),
choice(task('T01_NEU_03','07','Berechne für x = 2. Welche Erklärung unterscheidet die Schreibweisen richtig?','3x; x³; 3 + x',[field('3x',6),field('x³',8),field('3 + x',5)],'3x = 3 · x; x³ = x · x · x; 3 + x ist eine Addition. Die Werte sind 6, 8 und 5.',['Unterscheide Faktor, Hochzahl und Pluszeichen.','x³ bedeutet nicht 3 · x.','Setze 2 ein: 3 · 2; 2 · 2 · 2; 3 + 2.']),['3x ist ein Produkt, x³ eine Potenz und 3 + x eine Summe.','Alle drei bedeuten, dass x dreimal addiert wird.','3x und x³ sind immer gleich; nur 3 + x bedeutet etwas anderes.','3x bedeutet 3 + x; x³ bedeutet 3 · x.'],0),
choice(task('T01_NEU_04','08','Ein Rechteck ist x m breit und (x + 1/2) m lang. Wähle den Umfangsterm und berechne für x = 3/4.','',[field('Umfang (m)',4)],'U = 2x + 2(x + 1/2) = 4x + 1. Für x = 3/4 ergibt sich U = 4 m.',['Breite und Länge kommen jeweils zweimal vor.','2 · 1/2 = 1.','4 · 3/4 + 1 = 3 + 1.']),['U = 2x + 1/2','U = 4x + 1/2','U = 4x + 1','U = x(x + 1/2)'],2),
choice(task('T01_NEU_05','09','Wähle einen Term mit Variable x, Koeffizient −2 und konstantem Summanden 5 samt passender Erklärung.','',[],'−2x + 5: −2 ist der Zahlenfaktor von x; 5 bleibt bei jeder Eingabe gleich.',['Der Koeffizient steht als Faktor vor x.','Die Konstante enthält kein x.','Gesucht sind −2 mal x und danach plus 5.']),['5x − 2: Der Koeffizient ist die Zahl ohne x.','−2x + 5: −2 ist der Faktor vor x, 5 bleibt unabhängig von x gleich.','−2(x + 5): Die Konstante ist immer die Zahl, die in der Klammer steht.','−2x⁵: Die Hochzahl ist der konstante Summand.'],1),
task('T01_NEU_06','10','Berechne beide Termwerte für a = −1/2 und b = 2.','2a² − b und (2a)² − b',[field('Erster Termwert',-1.5),field('Zweiter Termwert',-1)],'2 · (−1/2)² − 2 = −1,5; (2 · (−1/2))² − 2 = −1.',['Im ersten Term wird nur a quadriert.','a² = 1/4, aber (2a)² = (−1)² = 1.','Rechne im ersten Term 1/2 − 2 und im zweiten 1 − 2.'])
];
MODULES.T01.check=[
task('T01_TEST_01','1','Berechne für x = −2.','T(x) = 5x − 7',[field('Termwert',-17)],'5 · (−2) − 7 = −10 − 7 = −17.'),
task('T01_TEST_02','2','Berechne für a = 3 und b = −1.','5a − 2b',[field('Termwert',17)],'5 · 3 − 2 · (−1) = 15 + 2 = 17.'),
ordering(task('T01_TEST_03','3','Ordne den Rechenplan von innen nach außen.','2(x + 5)²',[],'Zuerst einen Wert einsetzen, dann 5 addieren, die gesamte Summe quadrieren, das Quadrat verdoppeln und den Termwert angeben.'),['Einen Wert für x einsetzen.','Zu diesem Wert 5 addieren.','Die gesamte Summe quadrieren.','Das Quadrat mit 2 multiplizieren.','Das Ergebnis als Termwert angeben.']),
choice(task('T01_NEU_07','4','Wähle den Rechenplan und berechne für x = −1.','4(x + 2)²',[field('Termwert',4)],'Addiere 2, quadriere die Summe, vervierfache: 4 · (−1 + 2)² = 4.'),['x vervierfachen, 2 addieren, das Ergebnis quadrieren.','x quadrieren, 2 addieren, das Ergebnis vervierfachen.','Zu x zuerst 2 addieren, die Summe quadrieren, dann vervierfachen.','Zu x zuerst 2 addieren, das Ergebnis mit 4 multiplizieren, dann quadrieren.'],2),
choice(task('T01_NEU_08','5','Eine Fahrt kostet 3 Euro Grundpreis und 1,50 Euro pro Kilometer. Welche Erklärung passt?','1,5s + 3',[],'1,5 ist der Preis je Kilometer, 3 die einmalige Grundgebühr; s steht für die Strecke in Kilometern.'),['1,5 ist der Preis je Kilometer; 3 ist die Grundgebühr unabhängig von der Strecke.','1,5 ist die Grundgebühr; 3 ist der Preis je Kilometer.','1,5s ist ein fester Preis, denn die 1,5 ändert sich nicht.','3 wird für jeden Kilometer addiert, weil es ein Summand ist.'],0)
];
MODULES.B02.guide={idea:'Die Schreibweise ändert sich. Der Bruchwert bleibt gleich.',steps:DATA.topics.B02.steps,mini:task('B02_MINI','Erster Schritt','Kürze 12/18. Ergänze denselben Divisor im Nenner.','12/18 = (12 : 6)/(18 : □)',[field('Fehlender Divisor',6)],'Teile beide Zahlen durch 6: 12/18 = 2/3.',['Der Wert bleibt nur gleich, wenn oben und unten derselbe Divisor steht.','Im Zähler wird bereits durch 6 geteilt.','Verwende auch im Nenner die 6.'])};
MODULES.T01.guide={idea:'Eine Variable ist ein Platzhalter. Setze die Zahl vollständig ein und halte den Rechenplan ein.',steps:DATA.topics.T01.steps,mini:task('T01_MINI','Erster Schritt','Setze x = −2 ein und berechne.','T(x) = 3x + 1; T(−2) = 3 · (□) + 1',[field('Eingesetzte Zahl',-2),field('Termwert',-5)],'T(−2) = 3 · (−2) + 1 = −6 + 1 = −5.',['Ersetze x durch die ganze Zahl mit Vorzeichen.','3 · (−2) = −6.','Addiere zu −6 die Zahl 1.'])};
for(const m of Object.values(MODULES))for(const section of ['practice','pool','check'])for(const q of m[section])q.section=section;
