// The existing storage namespace is retained; legacy three-question checks remain history only.
state.taskWork??={};state.activeChecks??={};
const skillLabels={A1:'Startaufgabe',A2:'Noch einmal selbst',B:'Rückwärts denken',C:'Fehler verstehen',D:'Anwenden und begründen'};
function currentSection(){return route().split('/')[2]||'explain';}
function newWork(q){return {values:q.fields.map(()=>''),choice:null,order:q.steps?[2,0,4,1,3]:null,hints:0,feedback:null};}
function workKey(q,section=currentSection()){return `${topic()}:${section}:${q.id}`;}
function taskWork(q){const k=workKey(q);return state.taskWork[k]??(state.taskWork[k]=newWork(q));}
function selectedTask(){const m=MODULES[topic()],s=currentSection();return s==='guide'?m.guide.mini:m[s==='pool'?'pool':'practice'][Math.min(exerciseIndex,m[s==='pool'?'pool':'practice'].length-1)];}
function parseValue(value){const fraction=parseFraction(value);return fraction?fraction[0]/fraction[1]:parseNumber(value);}
function evaluateTask(q,w){
 for(let i=0;i<q.fields.length;i++){const f=q.fields[i],v=w.values[i];if(f.kind==='fraction'){const p=parseFraction(v);if(!p)return {correct:false,message:'Notiere den Bruch mit Schrägstrich, zum Beispiel 3/4.'};if(String(f.answer).startsWith('equiv:')){const a=parseFraction(f.answer.slice(6));if(p[0]*a[1]!==a[0]*p[1]||p.some(n=>n<=0||!Number.isSafeInteger(n)))return {correct:false,message:'Prüfe, ob alle Brüche denselben Wert haben.'};}else{const a=parseFraction(f.answer);if(p[0]!==a[0]||p[1]!==a[1])return {correct:false,message:p[0]*a[1]===a[0]*p[1]?'Der Bruchwert stimmt. Prüfe noch den verlangten Nenner oder kürze vollständig.':'Prüfe deine Rechnung noch einmal.'};}}else{const n=parseValue(v);if(!Number.isFinite(n)||Math.abs(n-f.answer)>1e-9)return {correct:false,message:'Prüfe deine Rechnung und die Vorzeichen noch einmal.'};}}
 if(q.id==='B02_NEU_05'){const p=w.values.map(parseFraction);if(new Set(p.map(a=>a.join('/'))).size!==3||!p.some(a=>a[0]===18))return {correct:false,message:'Die Bruchwerte stimmen. Gesucht sind drei verschiedene Brüche; einer davon mit Zähler 18.'};}
 if(q.options&&w.choice!==q.correct)return {correct:false,message:'Vergleiche die Erklärungen genau. Welche passt zur gesamten Aufgabe?'};
 if(q.steps&&w.order.some((n,i)=>n!==i))return {correct:false,message:'Prüfe die Reihenfolge: Welcher Schritt braucht das Ergebnis des vorherigen?'};
 return {correct:true,message:q.reason};
}
function workComplete(q,w){return q.fields.every((_,i)=>String(w.values[i]??'').trim())&&(!q.options||w.choice!==null)&&(!q.steps||w.orderTouched);}
function mathText(s){return esc(s).replace(/(?<![\w])(-?\d+)\/(\d+|□)/g,(_,a,b)=>frac(a,b));}
function taskInputs(q,w,locked=false){return `${q.math?`<div class="math formula">${mathText(q.math)}</div>`:''}${q.fields.length?`<div class="multi-fields">${q.fields.map((f,i)=>`<div class="field"><label for="value-${i}">${esc(f.label)}</label><input id="value-${i}" data-value-index="${i}" value="${esc(w.values[i])}" autocomplete="off" inputmode="text" required ${locked?'disabled':''} placeholder="${f.kind==='fraction'?'z. B. 3/4':'Zahl eingeben'}"></div>`).join('')}</div>`:''}${q.options?`<fieldset class="choice-fieldset"><legend>${q.fields.length?'Wähle die passende Erklärung.':'Wähle die beste Antwort.'}</legend>${q.options.map((o,i)=>`<label class="option"><input type="radio" name="explanation" data-choice-index="${i}" value="${i}" ${w.choice===i?'checked':''} ${locked?'disabled':''} required><span>${esc(o)}</span></label>`).join('')}</fieldset>`:''}${q.steps?`<p class="question-subtitle">Bringe die Schritte mit ↑ und ↓ in die richtige Reihenfolge.</p><ol class="order-list">${w.order.map((n,i)=>`<li class="order-item"><span class="order-number">${i+1}.</span><span class="order-text">${esc(q.steps[n])}</span><button type="button" data-move="${i}" data-direction="-1" aria-label="Schritt ${i+1} nach oben" ${i===0||locked?'disabled':''}>↑</button><button type="button" data-move="${i}" data-direction="1" aria-label="Schritt ${i+1} nach unten" ${i===q.steps.length-1||locked?'disabled':''}>↓</button></li>`).join('')}</ol>`:''}`;}
function exerciseView(q){const w=taskWork(q);return `<section class="card exercise-card"><p class="eyebrow">${esc(q.label)}${skillLabels[q.label]?' · '+skillLabels[q.label]:''}</p><h2>${typeof materialText==='function'?materialText(q.prompt):esc(q.prompt)}</h2><form id="exercise-form">${taskInputs(q,w,w.feedback?.correct)}<div class="actions"><button type="submit" class="primary" ${w.feedback?.correct?'disabled':''}>Antwort prüfen</button><button type="button" data-study-action="hint" ${w.hints>=q.hints.length||w.feedback?.correct?'disabled':''}>${w.hints?'Nächste Hilfe':'Kleine Hilfe'} · ${w.hints}/${q.hints.length}</button>${w.feedback?.correct?'<button type="button" data-study-action="retry-task">Noch einmal</button>':''}</div></form><div aria-live="polite">${q.hints.slice(0,w.hints).map((h,i)=>`<div class="hint"><strong>Hilfe ${i+1}</strong><br>${esc(h)}</div>`).join('')}${w.feedback?`<div class="feedback ${w.feedback.correct?'':'error'}"><strong>${w.feedback.correct?(w.hints?'Mit Hilfe gelöst.':'Richtig gelöst.'):'Noch nicht ganz.'}</strong><p>${esc(w.feedback.message)}</p></div>`:''}</div></section>`;}
practice=function(id){const section=currentSection()==='pool'?'pool':'practice',tasks=MODULES[id][section];exerciseIndex=Math.min(exerciseIndex,tasks.length-1);return `<div class="exercise-picker" aria-label="${section==='pool'?'Poolaufgabe':'Aufgabe'} auswählen">${tasks.map((q,i)=>{const attempts=state.attempts.filter(a=>a.topic===id&&a.taskId===q.id&&a.section===section);const solved=attempts.at(-1)?.correct;return `<button data-select-exercise="${i}" class="${i===exerciseIndex?'active':solved?'solved':attempts.length?'tried':''}" aria-pressed="${i===exerciseIndex}" title="${esc(q.label+': '+q.prompt)}">${esc(q.label)}${solved?'<small>✓</small>':''}</button>`}).join('')}</div>${exerciseView(tasks[exerciseIndex])}<div class="actions">${section==='practice'?`<a class="button" href="#learn/${id}/pool">Weitere Aufgaben im Pool</a>`:''}<a class="button" href="#learn/${id}/check">Zum Selbstcheck</a></div>`;};
function guide(id){const g=MODULES[id].guide;return `<section class="card"><h2>So funktioniert es in drei Schritten</h2><p>${esc(g.idea)}</p><ol class="three-steps">${g.steps.map(s=>'<li>'+esc(s)+'</li>').join('')}</ol></section><div class="guided-card">${exerciseView(g.mini)}</div><div class="actions"><a class="button" href="#learn/${id}/explain">Am Beispiel entdecken</a><a class="button primary" href="#learn/${id}/practice">Selbst üben</a></div>`;}
let exampleMode='square';termX=3;
const baseExplain=explain;
explain=function(id){if(id==='B02')return baseExplain(id).replace('<h3>Darauf kommt es an</h3>','<h3>Der Zusammenhang</h3>').replace('Jetzt selbst üben','Zur Drei-Schritt-Anleitung').replace(`href="#learn/${id}/practice"`,`href="#learn/${id}/guide"`);
 return `<section class="card term-discovery"><h2>Am Beispiel verstehen</h2><div class="term-idea"><strong>Ein Term ist eine Anleitung zum Rechnen.</strong><p>Die Variable x ist ein Platzhalter für eine Zahl. Setze dort deine Zahl ein und rechne nach der Anleitung. Das Ergebnis heißt <strong>Termwert</strong>.</p></div><div class="example-switch" aria-label="Beispiel auswählen"><button data-example="square" class="${exampleMode==='square'?'selected':''}" aria-pressed="${exampleMode==='square'}">2(x + 2)²</button><button data-example="linear" class="${exampleMode==='linear'?'selected':''}" aria-pressed="${exampleMode==='linear'}">3x − 7</button></div><div class="viz term-viz"><div class="term-definition math">${exampleMode==='linear'?'T(x) = 3 · <span class="term-substitution">x</span> − 7':'U(x) = 2 · (<span class="term-substitution">x</span> + 2)²'}</div><div class="term-input"><label class="slider-label" for="term-x">Setze für x eine Zahl ein: <output id="x-value"></output></label><input id="term-x" type="range" min="-5" max="5" step="1" value="${termX}"><div class="row small muted"><span>−5</span><span>0</span><span>5</span></div></div><div id="term-flow"></div><div class="dynamic term-result" id="dynamic-text" aria-live="polite" aria-atomic="true"></div></div><div class="actions"><a class="button primary" href="#learn/T01/guide">Zur Drei-Schritt-Anleitung</a><a class="button" href="#learn/T01/practice">Selbst üben</a></div></section>`;};
const baseViz=updateViz;
function termNumber(n){return String(n).replace('-','−');}
function termCalculation(x,mode){const n=termNumber(x),insert=`<span class="term-substitution">${x<0?'('+n+')':n}</span>`;if(mode==='linear')return {name:'T',result:3*x-7,steps:[{expression:`3 · ${insert} − 7`,label:'Einsetzen'},{expression:`${termNumber(3*x)} − 7`,label:'Multiplizieren'},{expression:termNumber(3*x-7),label:'Subtrahieren'}]};const sum=x+2,square=sum*sum;return {name:'U',result:2*square,steps:[{expression:`2 · (${insert} + 2)²`,label:'Einsetzen'},{expression:`2 · (${termNumber(sum)})²`,label:'Klammer ausrechnen'},{expression:`2 · ${square}`,label:'Quadrieren'},{expression:String(2*square),label:'Multiplizieren'}]};}
updateViz=function(){if(topic()!=='T01'){baseViz();return;}if(!$('#term-x'))return;const c=termCalculation(termX,exampleMode),n=termNumber(termX);$('#x-value').textContent=n;$('#term-flow').innerHTML=`<div class="term-calculation" aria-label="Termwert Schritt für Schritt berechnen">${c.steps.map((s,i)=>`<div class="term-line ${i===c.steps.length-1?'term-final-line':''}"><span class="term-left">${i===0?`${c.name}(<span class="term-substitution">${n}</span>)`:''}</span><span class="term-equals">=</span><span class="term-expression">${s.expression}</span><span class="term-step-note">${s.label}</span></div>`).join('')}</div>`;$('#dynamic-text').innerHTML=`Aus der eingesetzten Zahl <strong>${n}</strong> wird der Termwert <strong>${termNumber(c.result)}</strong>.`;};
function activeRun(id=topic()){const r=state.activeChecks[id];return r?.version===2?r:null;}
check=function(id){checkRun=activeRun(id);if(!checkRun)return `<section class="card"><h2>Was kannst du ohne Hilfe?</h2><p>Fünf Aufgaben aus dem Selbsttest. Lösungen gibt es nach der Abgabe.</p><label>Wie sicher fühlst du dich?</label><div class="pill-choice">${['Noch unsicher','Teils sicher','Ziemlich sicher'].map(c=>`<button data-confidence="${c}" class="${confidence===c?'selected':''}">${c}</button>`).join('')}</div><div class="actions"><button class="primary" data-study-action="start-check" ${!confidence?'disabled':''}>Check starten</button></div></section>`;
 if(checkRun.complete)return checkResult(id);const i=checkRun.index,q=MODULES[id].check[i],w=checkRun.work[i];return `<div class="check-overview" aria-label="Checkfrage auswählen">${MODULES[id].check.map((x,n)=>`<button data-check-index="${n}" class="${n===i?'active':workComplete(x,checkRun.work[n])?'answered':''}" aria-label="Frage ${n+1}${workComplete(x,checkRun.work[n])?' beantwortet':''}">${n+1}${workComplete(x,checkRun.work[n])?' ·':''}</button>`).join('')}</div><section class="card" style="margin-top:18px"><p class="eyebrow">Frage ${i+1} von 5</p><h2>${typeof materialText==='function'?materialText(q.prompt):esc(q.prompt)}</h2><form id="selfcheck-form">${taskInputs(q,w)}<div class="actions"><button type="submit" class="primary">${i===4?'Check auswerten':'Antwort übernehmen'}</button></div></form><div id="check-message" role="status"></div></section>`;};
function readableWork(q,w){const parts=q.fields.map((f,i)=>f.label+': '+w.values[i]);if(q.options)parts.push(q.options[w.choice]||'Keine Auswahl');if(q.steps)parts.push(w.order.map(n=>q.steps[n]).join(' → '));return parts.join(' · ');}
checkResult=function(id){const c=checkRun.record;return `<section class="card"><p class="eyebrow">Selbstcheck</p><h2>${c.correct} von 5 Aufgaben richtig</h2><p>${c.correct===5?'Das ist dir in diesem Check gelungen. Wiederhole später noch einmal.':'Die offenen Aufgaben zeigen dir, was du als Nächstes üben kannst.'}</p><p class="small muted">Vorher eingeschätzt: ${esc(c.confidence)}${c.assisted?' · Während des Checks andere Lernseiten geöffnet. Für einen Check ohne Hilfen starte später neu.':''}</p>${MODULES[id].check.map((q,i)=>`<details><summary>${c.answers[i].correct?'✓':'○'} Aufgabe ${i+1}: ${c.answers[i].correct?'richtig':'noch üben'}</summary><p>${typeof materialText==='function'?materialText(q.prompt):esc(q.prompt)}</p><p class="small muted">Deine Antwort: ${materialText(readableWork(q,checkRun.work[i]))}</p><p>${typeof materialText==='function'?materialText(q.reason):esc(q.reason)}</p></details>`).join('')}<form id="reflection-form" class="reflection"><label for="reflection">Was hilft dir beim nächsten Mal?</label><textarea id="reflection" required>${esc(state.reflections.find(r=>r.checkId===c.id)?.text||'')}</textarea><button type="submit">Reflexion speichern</button></form><div class="actions"><a class="button primary" href="#learn/${id}/${c.correct===5?'pool':'practice'}">${c.correct===5?'Weiter festigen':'Gezielt üben'}</a><button data-study-action="restart-check">Neuer Check</button><a class="button" href="#goals">Lernziel setzen</a></div><p class="small muted">Ein neuer Check enthält hier dieselben fünf Aufgaben. Mit zeitlichem Abstand ist der Abruf aussagekräftiger.</p></section>`;};
const baseBind=bindForms;
bindForms=function(){baseBind();$('#exercise-form')?.addEventListener('submit',e=>{e.preventDefault();const q=selectedTask(),w=taskWork(q);if(q.steps)w.orderTouched=true;const result=evaluateTask(q,w);w.feedback=result;state.attempts.push({topic:topic(),taskId:q.id,section:currentSection(),correct:result.correct,hints:w.hints,values:[...w.values],choice:w.choice,order:w.order?[...w.order]:null,date:today(),at:new Date().toISOString()});save();render();});$('#selfcheck-form')?.addEventListener('submit',e=>{e.preventDefault();const run=activeRun(),q=MODULES[topic()].check[run.index];if(q.steps)run.work[run.index].orderTouched=true;if(!workComplete(q,run.work[run.index]))return;if(run.index<4){run.index++;save();render();return;}const missing=MODULES[topic()].check.findIndex((q,i)=>!workComplete(q,run.work[i]));if(missing>=0){run.index=missing;save();render();$('#check-message').textContent='Diese Aufgabe ist noch offen. Bearbeite sie vor der Abgabe.';return;}const answers=MODULES[topic()].check.map((q,i)=>({...evaluateTask(q,run.work[i]),taskId:q.id}));const record={id:crypto.randomUUID(),topic:topic(),date:today(),at:new Date().toISOString(),answers,correct:answers.filter(a=>a.correct).length,total:5,confidence:run.confidence,assisted:!!run.assisted,version:2};state.checks.push(record);run.complete=true;run.record=record;save();render();});};
function visibleWork(){return currentSection()==='check'?activeRun()?.work[activeRun()?.index]:MODULES[topic()]&&['guide','practice','pool'].includes(currentSection())?taskWork(selectedTask()):null;}
document.addEventListener('input',e=>{const w=visibleWork();if(w&&e.target.dataset.valueIndex!==undefined){w.values[Number(e.target.dataset.valueIndex)]=e.target.value;w.feedback=null;save();}});
document.addEventListener('change',e=>{const w=visibleWork();if(w&&e.target.dataset.choiceIndex!==undefined){w.choice=Number(e.target.dataset.choiceIndex);w.feedback=null;save();}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;let handled=true;if(b.dataset.selectExercise!==undefined){exerciseIndex=Number(b.dataset.selectExercise);render();}else if(b.dataset.checkIndex!==undefined){activeRun().index=Number(b.dataset.checkIndex);save();render();}else if(b.dataset.move!==undefined){const w=visibleWork(),i=Number(b.dataset.move),j=i+Number(b.dataset.direction);if(j>=0&&j<w.order.length){[w.order[i],w.order[j]]=[w.order[j],w.order[i]];w.orderTouched=true;w.feedback=null;save();render();}}else if(b.dataset.example){exampleMode=b.dataset.example;render();}else if(b.dataset.studyAction){const a=b.dataset.studyAction;if(a==='hint'){const w=taskWork(selectedTask());w.hints=Math.min(w.hints+1,selectedTask().hints.length);save();render();}if(a==='retry-task'){state.taskWork[workKey(selectedTask())]=newWork(selectedTask());save();render();}if(a==='start-check'){state.activeChecks[topic()]={version:2,topic:topic(),index:0,confidence,work:MODULES[topic()].check.map(newWork),complete:false};save();render();}if(a==='restart-check'){delete state.activeChecks[topic()];checkRun=null;confidence='';save();render();}}else handled=false;if(handled){e.preventDefault();e.stopImmediatePropagation();lastActive=Date.now();}},true);
window.addEventListener('hashchange',()=>{for(const [id,r] of Object.entries(state.activeChecks))if(!r.complete&&route().startsWith('learn/')&&route()!==`learn/${id}/check`){r.assisted=true;save();}});
// Prototype topics not yet fully interactive still have real introductory content and timed reading.
window.addEventListener('hashchange',()=>{if(route().startsWith('learn/')&&DATA.topics[topic()]&&!MODULES[topic()]){startSession(topic());render();}});
if(route().startsWith('learn/')&&DATA.topics[topic()]&&!MODULES[topic()])startSession(topic());
const previousGoalValue=goalValue;
goalValue=function(g){const v=previousGoalValue(g);v.check=state.checks.some(c=>c.topic===g.topic&&c.date===g.date&&c.total===5&&c.correct===5&&!c.assisted&&(!g.createdAt||new Date(c.at)>=new Date(g.createdAt)));v.done=v.sec>=g.minutes*60&&(!g.check||v.check);return v;};
const previousProgress=progress;
progress=function(){return previousProgress().replaceAll(' · ohne Hilfe',' · Check abgeschlossen');};
