// Original orientation page and glossary, linked from the topic catalog.
let orientationIndex=0,orientationDraft='',orientationFeedback=null;
function orientationTask(index){const q=MATERIAL_SOURCE.orientation[index],answers=['20','\\frac7{12}','4','5','24','5x-8','5','5','60','250','5','\\frac35'],units={4:'Euro',8:'°',9:'cm²'};return {label:q[1],prompt:q[2],math:q[3],answer:answers[index],unit:units[index],form:index===5?'simplified':index===1?'reduced':undefined,reason:q[5],links:q[6]};}
function supportPage(){const q=orientationTask(orientationIndex);return `${pageHead('Orientierung und Fachwörter','', '<a class="button" href="#topics">Alle Themen</a>')}<section class="card"><h2>Wo möchtest du anfangen?</h2><div class="exercise-picker">${MATERIAL_SOURCE.orientation.map((x,i)=>`<button data-orientation="${i}" class="${i===orientationIndex?'active':''}" aria-label="${esc(x[1])}">${x[0]}</button>`).join('')}</div><h3>${esc(q.label)}</h3><p>${materialText(q.prompt)}</p>${q.math?`<div class="formula">${renderMath(q.math,true)}</div>`:''}<form id="orientation-form"><label for="orientation-answer">${q.unit?'Ergebnis in '+q.unit:'Deine Antwort'}</label><input id="orientation-answer" value="${esc(orientationDraft)}" autocomplete="off" required><div class="actions"><button class="primary" type="submit">Antwort prüfen</button></div></form>${orientationFeedback?`<div class="feedback ${orientationFeedback.correct?'':orientationFeedback.partial?'partial':'error'}"><strong>${orientationFeedback.correct?'Richtig.':orientationFeedback.partial?'Richtiger Zwischenstand.':'Noch nicht ganz.'}</strong><p>${materialText(orientationFeedback.correct?q.reason:orientationFeedback.message)}</p></div>`:''}<details><summary>Lösung und Denkschritte</summary><div class="worked-math">${renderMath(q.answer+(q.unit?'\\,\\text{'+q.unit+'}':''),true)}</div><p>${materialText(q.reason)}</p></details><div class="actions">${q.links.map(id=>`<a class="button" href="#learn/${id}/explain">${id} · ${esc(title(id))}</a>`).join('')}</div></section><section class="card glossary"><h2>Fachwörter nachschlagen</h2>${MATERIAL_SOURCE.glossary.map(([term,definition,id])=>`<details><summary>${esc(term)}</summary><p>${materialText(definition)}</p><a href="#learn/${id}/explain">Zum Thema ${id}: ${esc(title(id))}</a></details>`).join('')}</section>`;}
const supportPreviousTopics=topics;topics=function(){return supportPreviousTopics()+'<div class="actions support-link"><a class="button" href="#support">Orientierung und Fachwörter</a></div>';};
const supportPreviousBind=bindForms;bindForms=function(){supportPreviousBind();$('#orientation-form')?.addEventListener('submit',e=>{e.preventDefault();const previousSuccess=orientationFeedback?.correct&&orientationDraft===$('#orientation-answer').value;orientationDraft=$('#orientation-answer').value;const q=orientationTask(orientationIndex);orientationFeedback=MathAnswer.check(orientationDraft,{answer:q.answer,unit:q.unit,form:q.form,kind:'expression'});render();if(orientationFeedback.correct&&!previousSuccess)animateTaskSuccess('#orientation-form');});};
document.addEventListener('input',e=>{if(e.target.id==='orientation-answer')orientationDraft=e.target.value;});
document.addEventListener('click',e=>{const b=e.target.closest('button[data-orientation]');if(b?.dataset.orientation===undefined)return;e.preventDefault();e.stopImmediatePropagation();orientationIndex=Number(b.dataset.orientation);orientationDraft='';orientationFeedback=null;render();},true);
render();
