/* Safe input grammar + symbolic equivalence. No JavaScript evaluation of learner input. */
const MathAnswer=(()=>{
 const MAX_LENGTH=500;
 function latexToPlain(input){
  let s=String(input??'').trim().replace(/\u2212|\u2013/g,'-').replace(/\u00b7|\u00d7/g,'*').replace(/\u00f7/g,'/').replace(/\{,\}/g,',').replace(/\$|\\\(|\\\)|\\\[|\\\]/g,'');
  s=s.replace(/\\(?:left|right|displaystyle|quad|qquad|thinspace|,|;|!|\s)/g,'').replace(/\\(?:cdot|times)/g,'*').replace(/\\(?:div|colon)/g,'/').replace(/\\pi\b/g,'pi').replace(/π/g,'pi').replace(/\\(?:Box|square)/g,'□');
  function group(text,start){while(text[start]===' ')start++;if(text[start]==='{'){let d=1,i=start+1;for(;i<text.length&&d;i++){if(text[i]==='{')d++;if(text[i]==='}')d--;}if(d)throw Error('Klammer schließen.');return [text.slice(start+1,i-1),i];}if(text[start]==='\\'){const m=text.slice(start).match(/^\\[A-Za-z]+/);if(m)return [m[0],start+m[0].length];}return [text[start]||'',start+1];}
  for(let loop=0;loop<30;loop++){const m=s.match(/\\(?:dfrac|tfrac|frac|sqrt|mathrm|text|operatorname)/);if(!m)break;let start=m.index,end=start+m[0].length;const [a,ai]=group(s,end);let replacement;if(m[0].endsWith('frac')){const[b,bi]=group(s,ai);end=bi;replacement=`((${latexToPlain(a)})/(${latexToPlain(b)}))`;}else{end=ai;replacement=m[0]==='\\sqrt'?`sqrt(${latexToPlain(a)})`:a;}s=s.slice(0,start)+replacement+s.slice(end);}
  s=s.replace(/_\{([A-Za-z0-9]+)\}/g,'_$1').replace(/[{}]/g,m=>m==='{'?'(':')').replace(/\\%/g,'%').replace(/²/g,'^2').replace(/³/g,'^3').replace(/⁴/g,'^4').replace(/⁵/g,'^5').replace(/⁶/g,'^6').replace(/\^\(([-+]?\d+)\)/g,'^$1');
  if(/\d\.\d{3},\d/.test(s))s=s.replace(/\.(?=\d{3}(?:\D|$))/g,'');
  s=s.replace(/(\d),(?=\d)/g,'$1.').replace(/\b(\d+)\s+(\d+)\s*\/\s*(\d+)\b/g,'($1+$2/$3)').replace(/(\d)\s+(?=\d{3}(?:\D|$))/g,'$1').replace(/\s/g,'').replace(/:/g,'/').replace(/√\(([^()]*)\)/g,'sqrt($1)').replace(/√(\d+(?:\.\d+)?)/g,'sqrt($1)');
  if(/^[-+]?\d+(?:\.\d+)?[eE][-+]?\d+$/.test(s))s=s.replace(/([eE])([-+]?\d+)$/,'*10^($2)');
  if(s.includes('|'))s=s.replace(/\|([^|]+)\|/g,'abs($1)');
  return s;
 }
 function tokenize(s){if(!s||s.length>MAX_LENGTH)throw Error('Gib einen kurzen mathematischen Ausdruck ein.');let tokens=[],i=0;
  while(i<s.length){let m=s.slice(i).match(/^(?:\d+(?:\.\d*)?|\.\d+)/);if(m){tokens.push({type:'number',value:m[0]});i+=m[0].length;continue;}m=s.slice(i).match(/^(sqrt|abs|pi)(?![a-z_])/);if(m){tokens.push({type:m[1]==='pi'?'variable':'function',value:m[1]});i+=m[0].length;continue;}m=s.slice(i).match(/^[a-zA-Z](?:_[A-Za-z0-9]+)?/);if(m){tokens.push({type:'variable',value:m[0]});i+=m[0].length;continue;}if('+-*/^()%'.includes(s[i])){tokens.push({type:s[i],value:s[i]});i++;continue;}throw Error('Verwende Zahlen, Variablen, Klammern und Rechenzeichen.');}
  if(tokens.length>160)throw Error('Der Ausdruck ist zu lang.');tokens.push({type:'end'});return tokens;
 }
 function parse(raw){const source=latexToPlain(raw).replace(/pi(?=[A-Za-z])/g,'pi*'),tokens=tokenize(source);let i=0,nodes=0;
  function expression(min=0){if(++nodes>160)throw Error('Der Ausdruck ist zu lang.');let token=tokens[i++],left;
   if(token.type==='number')left={type:'number',value:token.value.replace(/^\./,'0.').replace(/\.$/,'.0')};else if(token.type==='variable')left={type:'variable',value:token.value};else if(token.type==='+'||token.type==='-')left={type:'unary',op:token.type,arg:expression(25)};else if(token.type==='('){left=expression();if(tokens[i++].type!==')')throw Error('Prüfe die Klammern.');}else if(token.type==='function'){if(tokens[i++].type!=='(')throw Error('Schreibe Funktionen mit Klammern, z. B. sqrt(9).');left={type:'function',name:token.value,arg:expression()};if(tokens[i++].type!==')')throw Error('Prüfe die Klammern.');}else throw Error('Hier fehlt eine Zahl oder Variable.');
   while(true){const t=tokens[i];if(t.type==='%'){i++;left={type:'binary',op:'/',left,right:{type:'number',value:'100'}};continue;}let op=t.type,implicit=['number','variable','function','('].includes(op),power=op==='+'||op==='-'?10:op==='*'||op==='/'||implicit?20:op==='^'?30:-1;if(power<min)break;if(implicit)op='*';else i++;const right=expression(op==='^'?power:power+1);left={type:'binary',op,left,right};}
   return left;
  }
  const ast=expression();if(tokens[i].type!=='end')throw Error('Prüfe die Schreibweise und die Klammern.');const vars=new Set();walk(ast,n=>{if(n.type==='variable'&&n.value!=='pi')vars.add(n.value);if(n.type==='number'&&(!Number.isFinite(Number(n.value))||Math.abs(Number(n.value))>1e15))throw Error('Die Zahl ist zu groß.');if(n.type==='binary'&&n.op==='^'){const p=constant(n.right);if(!Number.isInteger(p)||Math.abs(p)>15||(variables(n.left).size&&Math.abs(p)>6))throw Error('Verwende eine kleine ganzzahlige Potenz.');}});expansionCost(ast);if(!vars.size&&Math.abs(constant(ast))>1e100)throw Error('Die Zahl ist zu groß.');return {source,ast,vars,code:serialize(ast)};
 }
 function expansionCost(n){let cost;if(n.arg)cost=expansionCost(n.arg);else if(!n.left)cost=1;else{const a=expansionCost(n.left),b=expansionCost(n.right);cost=n.op==='+'||n.op==='-'?a+b:n.op==='^'?a**Math.abs(constant(n.right)):a*b;}if(cost>512||degree(n)>60)throw Error('Dieser Ausdruck ist zu groß zum Ausmultiplizieren. Vereinfache ihn zuerst.');return cost;}
 function degree(n){if(n.arg)return degree(n.arg);if(!n.left)return n.type==='variable'?1:0;const a=degree(n.left),b=degree(n.right);return n.op==='^'?a*Math.abs(constant(n.right)):n.op==='+'||n.op==='-'?Math.max(a,b):a+b;}
 function walk(n,fn){fn(n);if(n.left)walk(n.left,fn);if(n.right)walk(n.right,fn);if(n.arg)walk(n.arg,fn);}
 function variables(n){const v=new Set();walk(n,x=>{if(x.type==='variable'&&x.value!=='pi')v.add(x.value);});return v;}
 function serialize(n){if(n.type==='number'||n.type==='variable')return n.value;if(n.type==='unary')return `(${n.op}${serialize(n.arg)})`;if(n.type==='function')return `${n.name}(${serialize(n.arg)})`;return `(${serialize(n.left)}${n.op}${serialize(n.right)})`;}
 function constant(n){if(n.type==='number')return Number(n.value);if(n.type==='variable')return n.value==='pi'?Math.PI:NaN;if(n.type==='unary')return(n.op==='-'?-1:1)*constant(n.arg);if(n.type==='function')return n.name==='sqrt'?Math.sqrt(constant(n.arg)):Math.abs(constant(n.arg));const a=constant(n.left),b=constant(n.right);return n.op==='+'?a+b:n.op==='-'?a-b:n.op==='*'?a*b:n.op==='/'?a/b:a**b;}
 function cas(code){if(typeof nerdamer==='undefined')throw Error('Die mathematische Prüfung wird noch geladen.');const translated=code.replace(/[A-Za-z][A-Za-z0-9_]*/g,name=>['pi','sqrt','abs','expand','simplify','factor'].includes(name)?name:'v_'+name);return nerdamer(translated);}
 function casText(expression){return expression.toString().replace(/\bv_([A-Za-z][A-Za-z0-9_]*)\b/g,'$1');}
 function exactEqual(a,b){try{const diff=`(${a})-(${b})`;return cas(`expand(${diff})`).toString()==='0'||cas(`simplify(${diff})`).toString()==='0';}catch{return false;}}
 function constraints(ast){const nonzero=[],nonnegative=[];
  function factor(n){try{return parse(casText(cas(`factor(${serialize(n)})`))).ast;}catch{return n;}}
  function positiveEverywhere(n){if(!variables(n).size)return constant(n)>=0;if(n.type==='function'&&(n.name==='abs'||n.name==='sqrt'))return true;if(n.type==='binary'&&n.op==='^'&&constant(n.right)%2===0)return true;if(n.type==='binary'&&(n.op==='*'||n.op==='+'))return positiveEverywhere(n.left)&&positiveEverywhere(n.right);return false;}
  function strictlyPositive(n){if(!variables(n).size)return constant(n)>0;if(n.type==='binary'&&n.op==='+')return strictlyPositive(n.left)&&positiveEverywhere(n.right)||positiveEverywhere(n.left)&&strictlyPositive(n.right);if(n.type==='binary'&&n.op==='*')return strictlyPositive(n.left)&&strictlyPositive(n.right);if(n.type==='function'&&n.name==='sqrt')return strictlyPositive(n.arg);return false;}
  function add(n,factored=false){if(!variables(n).size){if(constant(n)===0)throw Error('Durch 0 darfst du nicht teilen.');return;}if(strictlyPositive(n))return;if(!factored){add(factor(n),true);return;}if(n.type==='binary'&&n.op==='*'){add(n.left,true);add(n.right,true);return;}if(n.type==='binary'&&n.op==='^'||n.type==='unary'){add(n.left||n.arg,true);return;}if(n.type==='function'&&(n.name==='sqrt'||n.name==='abs')){add(n.arg);return;}nonzero.push(serialize(n));}
  walk(ast,n=>{if(n.type==='binary'&&n.op==='/')add(n.right);if(n.type==='binary'&&n.op==='^'&&constant(n.right)<0)add(n.left);if(n.type==='function'&&n.name==='sqrt'){if(!variables(n.arg).size&&constant(n.arg)<0)throw Error('Die Quadratwurzel braucht hier eine nichtnegative Zahl.');if(!positiveEverywhere(factor(n.arg)))nonnegative.push(serialize(n.arg));}});return {nonzero,nonnegative};
 }
 function sameZeroSet(a,b){if(exactEqual(a,b))return true;try{const ratio=cas(`simplify((${a})/(${b}))`);return ratio.variables().length===0&&Number(ratio.evaluate().text())!==0;}catch{return false;}}
 function samePositiveRegion(a,b){if(exactEqual(a,b))return true;try{const ratio=cas(`simplify((${a})/(${b}))`);return ratio.variables().length===0&&Number(ratio.evaluate().text())>0;}catch{return false;}}
 function equivalent(a,b,tolerance=0){const ca=constraints(a.ast),cb=constraints(b.ast);for(const kind of ['nonzero','nonnegative']){const same=kind==='nonzero'?sameZeroSet:samePositiveRegion;if(ca[kind].some(x=>!cb[kind].some(y=>same(x,y)))||cb[kind].some(x=>!ca[kind].some(y=>same(x,y))))return {equal:false,domain:true};}if(!a.vars.size&&!b.vars.size){const va=constant(a.ast),vb=constant(b.ast);if(!Number.isFinite(va)||!Number.isFinite(vb))return {equal:false};return {equal:exactEqual(a.code,b.code)||(tolerance>0&&Math.abs(va-vb)<=tolerance)};}return {equal:exactEqual(a.code,b.code)};}
 function additiveTerms(n){if(n.type==='binary'&&(n.op==='+'||n.op==='-'))return [...additiveTerms(n.left),...additiveTerms(n.right)];return[n];}
 function monomial(n){if(n.type==='number'||n.type==='variable')return true;if(n.type==='unary')return monomial(n.arg);if(n.type==='function')return !variables(n).size;if(n.op==='^')return n.left.type==='variable'&&n.right.type==='number';if(n.op==='*')return monomial(n.left)&&monomial(n.right)&&!(n.left.type==='number'&&n.right.type==='number');if(n.op==='/')return monomial(n.left)&&!variables(n.right).size&&Number.isFinite(constant(n.right));return false;}
 function collected(p){const terms=additiveTerms(p.ast);if(!terms.every(monomial))return false;for(const term of terms){const seen=new Set();let repeat=false,numbers=0;function scan(n,inExponent=false){if(n.type==='variable'){if(seen.has(n.value))repeat=true;seen.add(n.value);}if(n.type==='binary'&&n.op==='*'&&(!variables(n.left).size&&[0,1].includes(Math.abs(constant(n.left)))||!variables(n.right).size&&[0,1].includes(Math.abs(constant(n.right)))))repeat=true;if(n.type==='binary'&&n.op==='^'&&constant(n.right)<=1)repeat=true;if(n.type==='number'&&!inExponent)numbers++;if(n.arg)scan(n.arg);if(n.left)scan(n.left);if(n.right)scan(n.right,n.op==='^'||n.op==='/');}scan(term);if(repeat||numbers>1)return false;}try{const expanded=parse(casText(cas(`expand(${p.code})`)));return additiveTerms(expanded.ast).length===terms.length;}catch{return false;}}
 function factored(p){let root=p.ast;if(root.type==='unary')root=root.arg;if(root.type!=='binary')return false;if(root.op==='^')return additiveTerms(root.left).length>1&&constant(root.right)>1;if(root.op!=='*')return false;const a=additiveTerms(root.left).length>1,b=additiveTerms(root.right).length>1;if(!a&&!b)return false;const factor=a?root.right:root.left;return variables(factor).size>0||Math.abs(constant(factor))!==1;}
 function simpleFraction(p){let n=p.ast,sign=1;if(n.type==='unary'){sign=n.op==='-'?-1:1;n=n.arg;}if(n.type==='number'&&Number.isInteger(Number(n.value)))return {a:sign*Number(n.value),b:1};if(n.type!=='binary'||n.op!=='/')return null;const a=constant(n.left)*sign,b=constant(n.right);return Number.isSafeInteger(a)&&Number.isSafeInteger(b)&&b!==0?{a,b}:null;}
 function gcd(a,b){a=Math.abs(a);b=Math.abs(b);while(b){const c=a%b;a=b;b=c;}return a;}
 function stripUnit(s,f){let unit=f.unit||'';if(!unit&&f.kind!=='expression'){const m=String(f.label||'').match(/(?:\(|\bin\s+)(mm|cm|dm|km|m|ml|cl|dl|l|kg|mg|g|s|min|h|€|%)([²³]|\^?[23])?(?:\)|\b)/i);if(m)unit=m[1]+(m[2]||'');}if(unit){const clean=String(s).trim();if(unit==='%')return clean.replace(/\s*%$/,'');const re=new RegExp('\\s*'+unit.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'$','i');return clean.replace(re,'');}return s;}
 function splitChain(raw){const s=String(raw).replace(/\\(?:approx|simeq)|≈/g,'=');if(/[<>≤≥≠]|\\(?:ne|le|ge)/.test(s))throw Error('Trage den gesuchten Wert oder Term ein.');return s.split('=').map(s=>s.trim()).filter(Boolean);}
 function expressionParts(raw){let parts=splitChain(raw);if(parts.length>1&&/^[A-Za-z](?:_[A-Za-z0-9]+|\([A-Za-z0-9-]+\))?$/.test(parts[0]))parts=parts.slice(1);else if(parts.length===2&&/^[A-Za-z]$/.test(parts[1]))parts=parts.slice(0,1);return parts;}
 function check(value,field){if(Array.isArray(field.acceptedAnswers)){const results=[field.answer,...field.acceptedAnswers].filter(a=>a!==undefined).map(answer=>check(value,{...field,answer,acceptedAnswers:undefined}));return results.find(r=>r.correct)||results.find(r=>r.partial)||results[0];}try{
  const raw=stripUnit(value,field),answer=String(field.answer),isEquiv=answer.startsWith('equiv:'),expectedParts=expressionParts(isEquiv?answer.slice(6):answer),expected=parse(expectedParts.at(-1));
  const parts=expressionParts(raw);if(!parts.length)return {correct:false,message:'Trage eine Antwort ein.'};const parsed=parts.map(parse),actual=parsed.at(-1);for(let i=1;i<parsed.length;i++)if(!equivalent(parsed[i-1],parsed[i]).equal)return {correct:false,message:'Prüfe deine Gleichheitszeichen: Nicht alle Schritte haben denselben Wert.'};
  const result=equivalent(actual,expected,field.tolerance??0);if(result.domain)return {correct:false,partial:true,message:'Prüfe die zulässigen Werte: Nenner dürfen nicht 0, Zahlen unter Quadratwurzeln nicht negativ sein.'};if(!result.equal)return {correct:false,message:'Prüfe deine Rechnung und die Vorzeichen noch einmal.'};
  const form=field.form;
  if((form==='simplified'||form==='expanded')&&!collected(actual))return {correct:false,partial:true,message:form==='expanded'?'Dein Term ist gleichwertig. Löse noch die Klammern auf und fasse zusammen.':'Das ist ein richtiger Schritt. Du kannst den Term noch weiter zusammenfassen.'};
  if(form==='factored'&&!factored(actual))return {correct:false,partial:true,message:'Der Term ist gleichwertig. Schreibe ihn noch als Produkt mit einem ausgeklammerten Faktor.'};
  const f=simpleFraction(actual),target=simpleFraction(expected);if((form==='reduced'||form==='fraction'||field.denominator)&&!f)return {correct:false,partial:true,message:'Der Wert stimmt. Gib die Antwort noch als Bruch an.'};
  if(form==='reduced'&&f&&(gcd(f.a,f.b)!==1||f.b<0))return {correct:false,partial:true,message:'Der Bruchwert stimmt. Kürze noch vollständig und schreibe den Nenner positiv.'};
  const denominator=field.denominator;if(denominator&&f&&f.b!==denominator)return {correct:false,partial:true,message:`Der Bruchwert stimmt. Schreibe den Bruch noch mit dem geforderten Nenner ${denominator}.`};
  if(form==='decimal'&&!/^[-+]?\d*(?:[.,]\d+)?$/.test(String(raw).trim()))return {correct:false,partial:true,message:'Der Wert stimmt. Schreibe die Antwort noch als Dezimalzahl.'};
  if(field.minTerms&&additiveTerms(actual.ast).length<field.minTerms)return {correct:false,partial:true,message:`Der Term ist gleichwertig. Verwende wie gefordert mindestens ${field.minTerms} Summanden.`};
  return {correct:true};
 }catch(e){return {correct:false,message:e.message||'Prüfe die Schreibweise. Brüche kannst du als 3/4, Potenzen als x^2 eingeben.'};}}
 return {latexToPlain,parse,serialize,constant,equivalent,collected,check,fractionParts:simpleFraction};
})();
if(typeof module!=='undefined'&&module.exports)module.exports=MathAnswer;
