// Compact topic groups and a day-based learning calendar. Existing learning data stays intact.
const expandedGroups=new Set();
let calendarMonth=today().slice(0,7),calendarDay=today(),calendarEditor=null,masonryObserver=null;
function groupState(ids){const states=ids.map(id=>learningStatus(id)),base=states.find(s=>s.color==='red')||states.find(s=>s.color==='yellow')||(states.length&&states.every(s=>s.color==='green')?states.find(s=>s.level==='practised')||states[0]:{color:'neutral',symbol:'○',label:'Noch nicht vollständig bearbeitet'}),review=states.find(s=>s.reviewDue);return review?{...base,reviewDue:true,reviewTopic:review.reviewTopic}:base;}
function prioritizedTestTopics(t=nextTest()){
 const priority=s=>s.color==='red'?0:s.rank===0?1:s.color==='yellow'?2:s.level==='practised'?3:4;
 return testScope(t).map(id=>({id,status:learningStatus(id,true),focus:t.new_topics.includes(id)})).sort((a,b)=>priority(a.status)-priority(b.status)||Number(b.focus)-Number(a.focus)||a.id.localeCompare(b.id)).map(item=>item.id);
}
function upcomingTestTopics(scope){
 if(!scope.length)return '<p class="muted">Kein weiterer Test geplant.</p>';
 const first=scope.slice(0,3).map(id=>topicLink(id,true)).join('');
 if(scope.length<=3)return first;
 const id=scope[3],status=learningStatus(id,true);
 return first+'<details class="upcoming-expand"><summary><span class="upcoming-preview" aria-hidden="true"><span class="topic-entry '+status.color+'"><span class="topic-code">'+id+'</span><span class="topic-name">'+esc(title(id))+'</span>'+statusMark(status)+'</span></span><span class="upcoming-expand-label"><span class="upcoming-arrow" aria-hidden="true">⌄</span><span class="upcoming-show">Alle Themen anzeigen ('+scope.length+')</span></span></summary><div class="upcoming-rest">'+scope.slice(3).map(id=>topicLink(id,true)).join('')+'</div><button type="button" class="upcoming-expand-label upcoming-collapse" data-upcoming-collapse><span class="upcoming-arrow" aria-hidden="true">⌃</span><span>Weniger anzeigen</span></button></details>';
}
topics=function(){const scope=prioritizedTestTopics();return `${pageHead('Lernen','')}${legend()}<section class="card upcoming-topics"><h2>Themen des nächsten Tests</h2>${upcomingTestTopics(scope)}</section><div class="section-break all-topics-heading"><h2>Alle Themen</h2>${overallTopicProgress()}</div><div class="topic-mosaic" id="topic-masonry">${Object.entries(GROUP_NAMES).map(([letter,name])=>{const ids=Object.keys(DATA.topics).filter(id=>id.startsWith(letter)),s=groupState(ids),complete=ids.filter(id=>learningStatus(id).level==='mastered').length,practised=ids.filter(id=>learningStatus(id).level==='practised').length,started=ids.filter(id=>learningStatus(id).color==='yellow').length,open=expandedGroups.has(letter);return `<section class="card group-block compact-group ${open?'expanded':''}" data-group="${letter}"><button class="group-toggle ${s.color}" data-toggle-group="${letter}" aria-expanded="${open}" aria-controls="group-${letter}"><span class="group-heading"><span class="group-letter">${letter}</span><span class="group-title">${name}</span>${statusMark(s)}<span class="group-chevron" aria-hidden="true">⌄</span></span><span class="group-count">${complete} / ${ids.length} mit Check${practised?' · '+practised+' gut geübt':''}${started?' · '+started+' in Arbeit':''}</span><span class="group-progress" aria-hidden="true"><i style="width:${100*complete/ids.length}%"></i><i class="practised-progress" style="width:${100*practised/ids.length}%"></i><b style="width:${100*started/ids.length}%"></b></span></button><div id="group-${letter}" class="group-body" ${open?'':'inert'}><div>${ids.map(id=>topicLink(id)).join('')}</div></div></section>`}).join('')}</div>`;};
function placeTopicGroups(){const box=$('#topic-masonry');if(!box||typeof box.getBoundingClientRect!=='function')return;const width=box.getBoundingClientRect().width,gap=16,columns=width>=1120?3:width>=620?2:1,cardWidth=(width-gap*(columns-1))/columns,heights=Array(columns).fill(0);box.classList.add('masonry-ready');for(const card of box.children){card.style.width=cardWidth+'px';const col=heights.indexOf(Math.min(...heights));card.style.transform=`translate(${col*(cardWidth+gap)}px, ${heights[col]}px)`;heights[col]+=card.getBoundingClientRect().height+gap;}box.style.height=Math.max(0,...heights)-gap+'px';}
function mountTopicGroups(){masonryObserver?.disconnect();const box=$('#topic-masonry');if(!box||typeof box.getBoundingClientRect!=='function')return;placeTopicGroups();if(typeof ResizeObserver!=='undefined'){masonryObserver=new ResizeObserver(placeTopicGroups);masonryObserver.observe(box);for(const card of box.children)masonryObserver.observe(card);}}
function testBadge(t){return `<span class="test-badge ${t.graded?'graded-badge':''}">${t.graded?'★ Bewerteter Test':'Grundwissenstest'}</span>`;}
tests=function(){const next=nextTest(),requested=Number(route().split('/')[1]);return `${pageHead('Tests','')}${legend()}<div class="test-planning">${getTests().map(t=>`<details id="test-${t.number}" class="card planned-test ${t.graded?'graded-test':''}" ${(requested||next?.number)===t.number?'open':''}><summary><span class="test-summary-title"><strong>Test ${String(t.number).padStart(3,'0')}</strong>${testBadge(t)}</span><span>${dateLabel(t.date)}${t.number===next?.number?' · als Nächstes':''}</span></summary><p class="small muted">${t.minutes} Minuten${t.graded?' · Alle bisher eröffneten Themen können vorkommen.':''}</p>${testScope(t).map(id=>topicLink(id,testScope().includes(id))).join('')}<details class="date-edit"><summary class="small">Termin anpassen</summary><label for="date-${t.number}">Datum auf diesem Gerät</label><input type="date" id="date-${t.number}" data-test-date="${t.number}" value="${t.date}"></details></details>`).join('')}</div>`;};
const calendarPreviousTestCard=testCard;
testCard=function(){const t=nextTest();return (t?.graded?'<div class="next-graded">'+testBadge(t)+'</div>':'')+calendarPreviousTestCard();};
function validDay(value){return /^\d{4}-\d{2}-\d{2}$/.test(value)&&dayKey(new Date(value+'T12:00:00'))===value;}
function monthDates(month){const [y,m]=month.split('-').map(Number),first=new Date(y,m-1,1,12),offset=(first.getDay()+6)%7,count=new Date(y,m,0).getDate();return Array.from({length:Math.ceil((offset+count)/7)*7},(_,i)=>i<offset||i>=offset+count?null:`${month}-${String(i-offset+1).padStart(2,'0')}`);}
function goalOutcome(g){const v=goalValue(g);return {...v,color:v.done?'green':g.date<today()?'missed':'pending',symbol:v.done?'✓':g.date<today()?'×':'○',label:v.done?'Erfüllt':g.date<today()?'Nicht erfüllt':'Noch offen'};}
function minuteLabel(seconds){return (Math.round(seconds/60*10)/10).toLocaleString('de-DE')+' Min.';}
function goalTopicSelection(id){return `${statusMark(learningStatus(id))}<span class="goal-topic-name">${id} · ${esc(title(id))}</span><span class="goal-topic-arrow" aria-hidden="true">⌄</span>`;}
function goalTopicPicker(selected){return `<span class="goal-topic-label" id="goal-topic-label">Thema</span><input type="hidden" name="topic" id="goal-topic-value" value="${esc(selected)}"><details class="goal-topic-picker" id="goal-topic-picker"><summary id="calendar-topic" aria-labelledby="goal-topic-label goal-topic-selected"><span id="goal-topic-selected">${goalTopicSelection(selected)}</span></summary><div class="goal-topic-options">${Object.entries(GROUP_NAMES).map(([letter,name])=>`<div role="group" aria-labelledby="goal-group-${letter}"><h4 id="goal-group-${letter}">${name}</h4>${Object.keys(DATA.topics).filter(id=>id.startsWith(letter)).map(id=>{const s=learningStatus(id);return `<button type="button" class="goal-topic-option ${s.color}" data-goal-topic="${id}" aria-pressed="${id===selected}"><span class="goal-topic-copy"><span>${id} · ${esc(title(id))}</span><small>${esc(s.label)}</small></span>${statusMark(s)}</button>`}).join('')}</div>`).join('')}</div></details>`;}
document.addEventListener('click',e=>{const b=e.target.closest('button[data-goal-topic]'),picker=$('#goal-topic-picker');if(b?.dataset.goalTopic&&picker){e.preventDefault();e.stopImmediatePropagation();const id=b.dataset.goalTopic;if(!DATA.topics[id])return;$('#goal-topic-value').value=id;$('#goal-topic-selected').innerHTML=goalTopicSelection(id);for(const choice of picker.querySelectorAll('[data-goal-topic]'))choice.setAttribute('aria-pressed',String(choice.dataset.goalTopic===id));picker.open=false;$('#calendar-topic').focus();}else if(picker?.open&&!picker.contains(e.target))picker.open=false;},true);
document.addEventListener('keydown',e=>{const picker=$('#goal-topic-picker');if(e.key==='Escape'&&picker?.open){e.preventDefault();picker.open=false;$('#calendar-topic').focus();}});
function daySessions(day){return allSessions().filter(s=>s.date===day&&s.seconds>0).sort((a,b)=>String(a.startedAt).localeCompare(String(b.startedAt)));}
function calendarCell(day){if(!day)return '<div class="calendar-empty" aria-hidden="true"></div>';const gs=state.goals.filter(g=>g.date===day),ss=daySessions(day),ts=getTests().filter(t=>t.date===day),past=day<today(),current=day===today();return `<div class="calendar-day ${past?'past':''} ${current?'is-today':''} ${calendarDay===day?'selected-day':''}"><div class="calendar-day-head"><button class="day-number" data-calendar-day="${day}" aria-label="${dateLabel(day)}${current?', heute':''}" ${current?'aria-current="date"':''} aria-pressed="${calendarDay===day}">${Number(day.slice(-2))}</button>${!past?`<button class="day-add" data-calendar-add="${day}" aria-label="Lernziel für ${dateLabel(day)} hinzufügen">+</button>`:''}</div><div class="calendar-events">${ts.map(t=>`<a class="calendar-test ${t.graded?'graded':''}" href="#tests/${t.number}" aria-label="${t.graded?'Bewerteter Test':'Test'} ${String(t.number).padStart(3,'0')} am ${dateLabel(day)}">${t.graded?'★ ':''}T${String(t.number).padStart(3,'0')}</a>`).join('')}${gs.map(g=>{const v=goalOutcome(g);return `<button class="calendar-goal ${v.color}" data-calendar-goal="${esc(g.id)}" aria-label="${g.topic}, ${g.minutes} Minuten, ${v.label}"><span>${g.topic}</span><span class="goal-symbol" aria-hidden="true">${v.symbol}</span></button>`}).join('')}${ss.length?`<button class="calendar-activity" data-calendar-day="${day}" aria-label="${minuteLabel(ss.reduce((n,s)=>n+s.seconds,0))} tatsächlich geübt">${minuteLabel(ss.reduce((n,s)=>n+s.seconds,0))}<span class="activity-label"> geübt</span></button>`:''}</div></div>`;}
function calendarGoalForm(){if(!calendarEditor||calendarDay<today())return '';const g=state.goals.find(x=>x.id===calendarEditor.id),id=g?.id||'',target=g?.topic||calendarEditor.topic||recommendation()?.id||'B02';return `<form id="calendar-goal-form" class="calendar-goal-form"><h3>${g?'Lernziel anpassen':'Lernziel hinzufügen'}</h3><input type="hidden" name="id" value="${esc(id)}"><input type="hidden" name="date" value="${calendarDay}"><div class="calendar-form-fields"><div class="field">${goalTopicPicker(target)}</div><div class="field duration-field"><label for="calendar-duration">Dauer in Minuten</label><input type="number" inputmode="numeric" id="calendar-duration" name="minutes" min="1" max="240" step="1" value="${g?.minutes||10}" required></div></div>${g?.check?'<p class="small muted">Zu diesem bestehenden Ziel gehört auch ein vollständig bestandener Check.</p>':''}<p class="small muted">Es zählt deine aktive Lernzeit zu diesem Thema am ausgewählten Tag, ab dem Anlegen des Ziels.</p><p id="calendar-form-error" class="form-error" role="alert"></p><div class="actions"><button type="submit" class="primary">${g?'Änderung speichern':'Ziel speichern'}</button><button type="button" data-calendar-action="cancel">Abbrechen</button></div></form>`;}
function calendarDayDetail(){const gs=state.goals.filter(g=>g.date===calendarDay),ss=daySessions(calendarDay),ts=getTests().filter(t=>t.date===calendarDay);return `<section class="card calendar-detail" id="calendar-detail" tabindex="-1"><div class="card-heading"><h2>${dateLabel(calendarDay)}${calendarDay===today()?' · Heute':''}</h2>${calendarDay>=today()&&!calendarEditor?`<button data-calendar-add="${calendarDay}">+ Lernziel</button>`:''}</div>${ts.length?`<div class="day-tests">${ts.map(t=>`<a class="day-test-link ${t.graded?'graded':''}" href="#tests/${t.number}">${t.graded?'★ Bewerteter Test':'Grundwissenstest'} ${String(t.number).padStart(3,'0')} <span aria-hidden="true">→</span></a>`).join('')}</div>`:''}${calendarGoalForm()}<div class="day-goals">${gs.length?gs.map(g=>{const v=goalOutcome(g);return `<div class="day-goal"><span class="goal-symbol ${v.color}" role="img" aria-label="${v.label}">${v.symbol}</span><div class="day-goal-text"><a href="#learn/${g.topic}/explain">${g.topic} · ${esc(title(g.topic))}</a><span>${g.minutes} Min. geplant · ${minuteLabel(v.sec)} geübt${g.check?' · mit Check':''}</span><span class="outcome-label ${v.color}">${v.label}</span></div>${g.date>=today()?`<button class="quiet" data-calendar-goal="${esc(g.id)}" aria-label="Lernziel ${g.topic} anpassen">Ändern</button>`:''}</div>`}).join(''):!calendarEditor?'<p class="muted small">Für diesen Tag sind keine Lernziele eingetragen.</p>':''}</div><div class="day-practice"><h3>Tatsächlich geübt</h3>${ss.length?ss.map(s=>`<div class="practice-record"><span class="practice-time">${new Date(s.startedAt).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}</span><a href="#learn/${s.topic}/explain">${s.topic} · ${esc(title(s.topic))}</a><strong>${fmtSec(s.seconds)}<span class="sr-only"> Minuten und Sekunden</span></strong></div>`).join(''):'<p class="muted small">An diesem Tag wurde noch keine Lernzeit aufgezeichnet.</p>'}</div></section>`;}
goals=function(){const heading=new Date(calendarMonth+'-01T12:00:00').toLocaleDateString('de-DE',{month:'long',year:'numeric'});return `<div class="calendar-page">${pageHead('Meine Ziele','')}<section class="card month-card"><div class="month-toolbar"><h2 id="month-heading">${heading}</h2><div class="month-navigation"><button data-calendar-action="prev" aria-label="Vorheriger Monat">‹</button><button data-calendar-action="today">Heute</button><button data-calendar-action="next" aria-label="Nächster Monat">›</button></div></div><div class="month-calendar" aria-labelledby="month-heading">${['Mo','Di','Mi','Do','Fr','Sa','So'].map(d=>`<div class="calendar-weekday">${d}</div>`).join('')}${monthDates(calendarMonth).map(calendarCell).join('')}</div><div class="calendar-key"><span>★ Bewerteter Test</span><span>✓ Ziel erfüllt</span><span>× Ziel nicht erfüllt</span><span>○ Noch offen</span></div></section>${calendarDayDetail()}</div>`;};
function saveCalendarGoal(values){const id=String(values.id||''),old=state.goals.find(g=>g.id===id),date=String(values.date||''),minutes=Number(values.minutes),topic=String(values.topic||'');if(id&&!old)return 'Das Lernziel wurde nicht gefunden.';if(!validDay(date)||date<today()||old?.date<today())return 'Wähle heute oder einen zukünftigen Tag.';if(!DATA.topics[topic])return 'Wähle ein Thema.';if(!Number.isInteger(minutes)||minutes<1||minutes>240)return 'Gib eine Dauer zwischen 1 und 240 Minuten ein.';if(state.goals.some(g=>g.id!==id&&g.date===date&&g.topic===topic))return 'Für dieses Thema gibt es an dem Tag schon ein Ziel. Du kannst es über „Ändern“ anpassen.';const now=new Date().toISOString(),g={...(old||{}),id:id||crypto.randomUUID(),topic,date,minutes,check:old?.check||false,createdAt:old?.createdAt||now,updatedAt:now};delete g.time;if(old){g.history=[...(old.history||[]),{...old,history:undefined}];state.goals[state.goals.indexOf(old)]=g;}else state.goals.push(g);save();return '';}
const calendarPreviousBindForms=bindForms;
bindForms=function(){calendarPreviousBindForms();$('#calendar-goal-form')?.addEventListener('submit',e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.target)),error=saveCalendarGoal(values);if(error){$('#calendar-form-error').textContent=error;return;}calendarEditor=null;render();$('#calendar-detail')?.focus?.({preventScroll:true});toast('Dein Lernziel ist gespeichert.');});};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.upcomingCollapse!==undefined){e.preventDefault();e.stopImmediatePropagation();const panel=b.closest('.upcoming-expand');panel.removeAttribute('open');const summary=panel.querySelector('summary');summary.focus({preventScroll:true});summary.scrollIntoView?.({block:'nearest'});return;}if(d.toggleGroup){e.preventDefault();e.stopImmediatePropagation();const group=b.closest('[data-group]'),open=!expandedGroups.has(d.toggleGroup);if(open)expandedGroups.add(d.toggleGroup);else expandedGroups.delete(d.toggleGroup);group.classList.toggle('expanded',open);b.setAttribute('aria-expanded',String(open));group.querySelector('.group-body').inert=!open;return;}if(!d.calendarAction&&!d.calendarDay&&!d.calendarAdd&&!d.calendarGoal)return;e.preventDefault();e.stopImmediatePropagation();let focusForm=false;if(d.calendarAction){if(d.calendarAction==='today'){calendarMonth=today().slice(0,7);calendarDay=today();}else if(d.calendarAction==='prev'||d.calendarAction==='next'){const [y,m]=calendarMonth.split('-').map(Number),next=new Date(y,m-1+(d.calendarAction==='next'?1:-1),1,12);calendarMonth=dayKey(next).slice(0,7);calendarDay=calendarMonth===today().slice(0,7)?today():calendarMonth+'-01';}calendarEditor=null;}if(d.calendarDay){calendarDay=d.calendarDay;calendarEditor=null;}if(d.calendarAdd){calendarDay=d.calendarAdd;calendarEditor={};focusForm=true;}if(d.calendarGoal){const g=state.goals.find(x=>x.id===d.calendarGoal);if(!g)return;calendarDay=g.date;calendarEditor=g.date>=today()?{id:g.id}:null;focusForm=!!calendarEditor;}render();if(focusForm)$('#calendar-topic')?.focus?.();else if(!d.calendarAction)$('#calendar-detail')?.focus?.({preventScroll:true});},true);
const calendarPreviousRender=render;
const statusPreviousBindForms=bindForms;
bindForms=function(){statusPreviousBindForms();$('#topic-status-form')?.addEventListener('submit',e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.target));if(!setTopicStatus(values.topic,values.level))return;render();$('#topic-status-editor')?.querySelector?.('summary')?.focus();});};
render=function(){calendarPreviousRender();mountTopicGroups();const match=route().match(/^tests\/(\d+)$/);if(match&&typeof requestAnimationFrame==='function')requestAnimationFrame(()=>$('#test-'+match[1])?.scrollIntoView?.({block:'start'}));};
