const GROUP_NAMES={N:'Natürliche Zahlen',B:'Brüche',D:'Dezimalzahlen',R:'Rationale Zahlen',P:'Prozent & Zinsen',T:'Terme',E:'Gleichungen',F:'Funktionen',G:'Geometrie',M:'Größen & Messen',S:'Statistik',W:'Wahrscheinlichkeit'};
function testScope(t=nextTest()){return t?[...new Set(t.graded?t.assessment_scope:[...t.new_topics,...t.review_topics])]:[];}
function calculatedLearningStatus(id,required=testScope().includes(id)){
 const attempts=state.attempts.filter(a=>a.topic===id),checks=state.checks.filter(c=>c.topic===id),last=checks.at(-1);
 const solved=new Set(attempts.filter(a=>a.correct&&a.taskId&&a.section!=='guide'&&a.section!=='check').map(a=>a.taskId)).size;
 const practised=solved>=5;
 const started=attempts.length>0||checks.length>0||allSessions().filter(s=>s.topic===id).reduce((n,s)=>n+s.seconds,0)>=15;
 if(practised&&last?.total===5&&last.correct===5&&!last.assisted)return {color:'green',level:'mastered',symbol:'✓✓',label:'Gut geübt und Check bestanden',rank:4};
 if(practised)return {color:'green',level:'practised',symbol:'✓',label:last&&last.correct<last.total?'Gut geübt · Im Check noch Lücken':'Gut geübt · Check noch offen',rank:last&&last.correct<last.total?0:2};
 if(last&&last.correct<last.total)return {color:'yellow',symbol:'◐',label:'Im Check noch Lücken',rank:0};
 if(started)return {color:'yellow',symbol:'◐',label:`In Bearbeitung · ${solved} von 5 Übungsaufgaben richtig`,rank:1};
 return {color:required?'red':'neutral',symbol:required?'!':'○',label:required?'Für den nächsten Test noch offen':'Noch nicht bearbeitet',rank:1};
}
const MANUAL_TOPIC_LEVELS={open:{symbol:'○',label:'Noch offen',rank:1},working:{color:'yellow',symbol:'◐',label:'In Bearbeitung',rank:1},practised:{color:'green',level:'practised',symbol:'✓',label:'Verstanden / gut geübt',rank:2},mastered:{color:'green',level:'mastered',symbol:'✓✓',label:'Gut geübt und Check bestanden',rank:4}};
function baseLearningStatus(id,required=testScope().includes(id)){const chosen=state.statusOverrides?.[id]?.level;if(!Object.hasOwn(MANUAL_TOPIC_LEVELS,chosen))return calculatedLearningStatus(id,required);if(chosen==='open')return {color:required?'red':'neutral',symbol:required?'!':'○',label:required?'Für den nächsten Test noch offen':'Noch nicht bearbeitet',rank:1,manual:true};return {...MANUAL_TOPIC_LEVELS[chosen],manual:true};}
function learningStatus(id,required=testScope().includes(id)){const s=baseLearningStatus(id,required);return needsTopicReview(id,s,required)?{...s,reviewDue:true,reviewTopic:id}:s;}
function setTopicStatus(id,level){if(!DATA.topics[id]||(level!=='auto'&&!Object.hasOwn(MANUAL_TOPIC_LEVELS,level)))return false;state.statusOverrides??={};if(level==='auto')delete state.statusOverrides[id];else state.statusOverrides[id]={level,updatedAt:new Date().toISOString()};save();return true;}
function topicGroupPicker(id){
 const group=id[0],ids=Object.keys(DATA.topics).filter(key=>key.startsWith(group)).sort((a,b)=>a.localeCompare(b,'de',{numeric:true}));
 const section=['explain','guide','practice','pool','check','ai','challenge'].includes(currentSection())?currentSection():'explain';
 return '<details class="topic-picker" id="topic-picker"><summary class="topic-heading-title"><h1><span>'+esc(title(id))+'</span><span class="topic-picker-arrow" aria-hidden="true">⌄</span></h1>'+statusMark(learningStatus(id))+'</summary><div class="topic-picker-list" role="navigation" aria-label="Themenbereich '+esc(GROUP_NAMES[group])+'"><div class="topic-picker-label">'+esc(GROUP_NAMES[group])+'</div>'+ids.map(key=>{const status=learningStatus(key),destination=section==='challenge'&&!MODULES[key]?.challenge?.tasks?.length?'practice':section;return '<a class="topic-entry '+status.color+'" href="#learn/'+key+'/'+destination+'" data-topic-switch="'+key+'"'+(key===id?' aria-current="page"':'')+'><span class="topic-code">'+key+'</span><span class="topic-name">'+esc(title(key))+'</span>'+statusMark(status)+'</a>';}).join('')+'</div></details>';
}
document.addEventListener('click',e=>{
 const picker=document.querySelector('#topic-picker');if(!picker?.open)return;
 if(e.target.closest('a[data-topic-switch]')||!picker.contains(e.target))picker.open=false;
});
document.addEventListener('keydown',e=>{
 const picker=document.querySelector('#topic-picker');if(e.key==='Escape'&&picker?.open){e.preventDefault();picker.open=false;picker.querySelector('summary')?.focus();}
});
function topicHeading(id){const s=learningStatus(id),override=state.statusOverrides?.[id]?.level,selected=Object.hasOwn(MANUAL_TOPIC_LEVELS,override)?override:'auto',auto=calculatedLearningStatus(id);return `<div class="page-head topic-page-head"><div class="topic-heading-text">${topicGroupPicker(id)}<p class="topic-heading-status">${id} · ${esc(s.label)}${s.manual?' · Manuell eingestellt':''}</p></div><div class="topic-heading-actions"><a class="button" href="#topics">Alle Themen</a><details class="topic-status-editor" id="topic-status-editor"><summary>Status ändern</summary><form class="topic-status-panel" id="topic-status-form"><input type="hidden" name="topic" value="${id}"><fieldset><legend>Dein Status für ${id}</legend><label class="topic-status-choice"><input type="radio" name="level" value="auto" ${selected==='auto'?'checked':''}>${statusMark(auto)}<span>Automatisch berechnen<small>${esc(auto.label)}</small></span></label>${Object.entries(MANUAL_TOPIC_LEVELS).map(([level,value])=>`<label class="topic-status-choice"><input type="radio" name="level" value="${level}" ${selected===level?'checked':''}>${statusMark(level==='open'?{...value,color:testScope().includes(id)?'red':'neutral',symbol:testScope().includes(id)?'!':'○'}:value)}<span>${esc(value.label)}</span></label>`).join('')}</fieldset><p class="small muted">Deine Auswahl gilt, bis du wieder „Automatisch berechnen“ wählst. Aufgezeichnete Übungen und Checks bleiben erhalten.</p><div class="actions"><button class="primary" type="submit">Übernehmen</button><button type="button" data-status-cancel="true">Abbrechen</button></div></form></details></div></div>`;}
function topicProgressTotals(){const states=Object.keys(DATA.topics).map(id=>learningStatus(id));return {total:states.length,complete:states.filter(s=>s.level==='mastered').length,practised:states.filter(s=>s.level==='practised').length,working:states.filter(s=>s.color==='yellow').length};}
function overallTopicProgress(){const p=topicProgressTotals(),label=`${p.complete} von ${p.total} abgeschlossen · ${p.practised} gut geübt · ${p.working} in Arbeit`,width=n=>p.total?100*n/p.total:0;return `<div class="overall-topic-progress"><div class="overall-progress-label">${label}</div><div class="group-progress overall-progress-bar" role="progressbar" aria-label="Gesamtfortschritt aller Themen" aria-valuemin="0" aria-valuemax="${p.total}" aria-valuenow="${p.complete}" aria-valuetext="${label}"><i style="width:${width(p.complete)}%"></i><i class="practised-progress" style="width:${width(p.practised)}%"></i><b style="width:${width(p.working)}%"></b></div></div>`;}
document.addEventListener('click',e=>{const b=e.target.closest('button[data-status-cancel]');if(!b?.dataset.statusCancel)return;e.preventDefault();e.stopImmediatePropagation();const editor=$('#topic-status-editor');if(editor){editor.open=false;editor.querySelector('summary')?.focus();}},true);
document.addEventListener('keydown',e=>{const editor=$('#topic-status-editor');if(e.key==='Escape'&&editor?.open){e.preventDefault();editor.open=false;editor.querySelector('summary')?.focus();}});
function status(id){return learningStatus(id).label;}
function statusMark(s){const label=esc(s.label+(s.manual?' · Manuell eingestellt':''));const mark=`<span class="state-mark ${s.color} ${s.level||''}" aria-label="${label}" title="${label}">${s.symbol}</span>`;return s.reviewDue?`<span class="status-with-review" data-review-topic="${esc(s.reviewTopic)}">${mark}<span class="review-mark" role="img" aria-label="Seit mindestens vier Wochen nicht bearbeitet: kurz wiederholen" title="Seit mindestens vier Wochen nicht bearbeitet. Wiederhole kurz, ob es noch sicher geht.">?</span></span>`:mark;}
function topicLink(id,required=testScope().includes(id)){const s=learningStatus(id,required);return `<a class="topic-entry ${s.color}" href="#learn/${id}/explain"><span class="topic-code">${id}</span><span class="topic-name">${esc(title(id))}</span>${statusMark(s)}</a>`;}
function legend(){return '<div class="status-legend"><span><b class="state-mark red">!</b> Für den Test offen</span><span><b class="state-mark yellow">◐</b> In Bearbeitung</span><span title="Mindestens fünf verschiedene Übungsaufgaben richtig gelöst"><b class="state-mark green">✓</b> Gut geübt · 5 Aufgaben</span><span><b class="state-mark green mastered">✓✓</b> Gut geübt + Check bestanden</span><span title="Der Hinweis verschwindet, sobald du wieder mit dem Lerninhalt interagierst."><b class="review-mark">?</b> Nach 4 Wochen kurz wiederholen</span></div>';}
function recommendation(){const t=nextTest(),scope=testScope(t);if(!scope.length)return null;const ordered=scope.map(id=>({id,s:learningStatus(id),focus:t.new_topics.includes(id)})).sort((a,b)=>a.s.rank-b.s.rank||Number(b.focus)-Number(a.focus)||a.id.localeCompare(b.id));const r=ordered[0];return {...r,reason:r.s.rank===0?'Im letzten Check sind noch Lücken aufgetaucht. Dieses Thema kommt im nächsten Test vor.':r.s.color==='red'?'Für den nächsten Test steht dieses Thema noch auf offen.':r.s.level==='mastered'?'Alle Themen für den nächsten Test stehen auf abgeschlossen. Festige dieses Thema noch einmal.':r.s.level==='practised'?(r.s.manual?'Du hast dieses Thema als verstanden markiert. Mit dem Check kannst du es überprüfen.':'Du hast mindestens fünf verschiedene Aufgaben richtig gelöst. Prüfe jetzt, was du ohne Hilfe kannst.'):'Dieses Thema ist noch in Bearbeitung. Arbeite daran weiter.',step:r.s.rank===0?'practice':r.s.level==='practised'?'check':r.s.level==='mastered'?'practice':'explain'};}
function testCard(){const t=nextTest();if(!t)return '<h2>Nächster Test</h2><p>Aktuell steht kein weiterer Test an.</p><a class="button" href="#tests">Testplanung</a>';return `<div class="card-heading"><h2>Nächster Test</h2><a href="#tests" class="small">Alle Tests</a></div><div class="test-headline"><strong>Test ${String(t.number).padStart(3,'0')}</strong><span>${dateLabel(t.date)} · ${t.minutes} Minuten${t.graded?' · bewertet':''}</span></div><div class="test-topic-list">${testScope(t).map(id=>topicLink(id,true)).join('')}</div>${t.graded?'<p class="small muted">Alle bisher eröffneten Themen können vorkommen.</p>':''}`;}
function dashboard(){const r=recommendation();return `<div class="simple-dashboard">${pageHead('Deine Übersicht','')}<section class="card">${testCard()}</section><section class="card next-step"><h2>Dein nächster Schritt</h2>${r?`<div class="recommended-title">${statusMark(r.s)}<h3>${r.id} · ${esc(title(r.id))}</h3></div><p class="muted">${r.reason}</p><a class="button primary" href="#learn/${r.id}/${MODULES[r.id]?r.step:'explain'}">${r.step==='check'&&MODULES[r.id]?'Zum Check':'Zum Thema'}</a>`:'<p>Wähle im Lernbereich, was du als Nächstes üben möchtest.</p><a class="button primary" href="#topics">Thema auswählen</a>'}</section></div>`;}
function topics(){const scope=testScope();return `${pageHead('Lernen','')}${legend()}<section class="card upcoming-topics"><h2>Themen des nächsten Tests</h2>${scope.length?scope.map(id=>topicLink(id,true)).join(''):'<p class="muted">Kein weiterer Test geplant.</p>'}</section><div class="section-break"><h2>Alle Themen</h2><span class="small muted">Nach Bereichen sortiert</span></div><div class="topic-mosaic">${Object.entries(GROUP_NAMES).map(([letter,name])=>{const ids=Object.keys(DATA.topics).filter(id=>id.startsWith(letter));const complete=ids.filter(id=>learningStatus(id).color==='green').length,started=ids.filter(id=>learningStatus(id).color==='yellow').length;return `<section class="card group-block"><div class="group-heading"><span class="group-letter">${letter}</span><h3>${name}</h3></div><div class="small muted">${complete} von ${ids.length} abgeschlossen${started?' · '+started+' in Arbeit':''}</div><div class="group-progress" aria-label="${complete} von ${ids.length} abgeschlossen; ${started} in Bearbeitung"><i style="width:${100*complete/ids.length}%"></i><b style="width:${100*started/ids.length}%"></b></div>${ids.map(id=>topicLink(id)).join('')}</section>`}).join('')}</div>`;}
const firstLearn=()=>{const id=topic(),step=route().split('/')[2]||'explain';return `<div class="learning">${topicHeading(id)}<div class="learning-tabs">${[['explain','Entdecken'],['guide','Erklärung'],['practice','Üben'],['pool','Übungspool'],['check','Check']].map(([s,t])=>`<a href="#learn/${id}/${s}" class="${step===s?'active':''}" ${step===s?'aria-current="page"':''}>${t}</a>`).join('')}</div>${step==='explain'?explain(id):step==='guide'?guide(id):step==='check'?check(id):practice(id)}</div>`;};
function learn(){if(!MODULES[topic()]){const id=topic(),t=DATA.topics[id];if(!t)return topics();return `<div class="learning">${topicHeading(id)}<section class="card"><h2>Darum geht es</h2><p>${esc(t.idea)}</p>${t.steps?'<h3>So funktioniert es in drei Schritten</h3><ol class="three-steps">'+t.steps.map(s=>'<li>'+esc(s)+'</li>').join('')+'</ol>':''}<p class="notice">Wähle in der Themenübersicht einen Lernbereich aus.</p><a class="button" href="#topics">Zur Themenübersicht</a></section></div>`;}return firstLearn();}
tests=function(){const next=nextTest();return `${pageHead('Tests','')}${legend()}<div class="test-planning">${getTests().map(t=>`<details class="card planned-test" ${t.number===next?.number?'open':''}><summary><strong>Test ${String(t.number).padStart(3,'0')}</strong><span>${dateLabel(t.date)} · ${t.graded?'bewertet':'unbewertet'}${t.number===next?.number?' · als Nächstes':''}</span></summary><p class="small muted">${t.minutes} Minuten${t.graded?' · Gesamter bisher eröffneter Stoff':''}</p>${testScope(t).map(id=>topicLink(id,testScope().includes(id))).join('')}<details class="date-edit"><summary class="small">Termin anpassen</summary><label for="date-${t.number}">Datum auf diesem Gerät</label><input type="date" id="date-${t.number}" data-test-date="${t.number}" value="${t.date}"></details></details>`).join('')}</div>`;};
